import { useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { SUBSCRIPTION_PLANS, isSubscriptionActive } from "@nivasafe/domain";
import { api, clearSession, download, getCurrentRole, getSession, isSessionRemembered, saveSession, useLoad } from "../../api/client";
import { EmptyState, Icon, PageHeader, SectionCard, StatusBadge, formatDate, type IconName, useDialog } from "../../components/UI";
import { AutoSaveForm, clearAutoSaveDraft } from "../../forms/AutoSaveForm";
import { scopedDraftKey } from "../../forms/autoSave";
import { useI18n } from "../../i18n";

export function LoadState<T>({ state, children, empty }: { state: ReturnType<typeof useLoad<T>>; children: (data: T) => ReactNode; empty?: string }) {
  const { t } = useI18n();
  if (state.loading) return <div className="state"><div className="spinner"/><p>{t("common.loading")}</p></div>;
  if (state.error) return <div className="state error-state"><span className="state-icon"><Icon name="warning" size={27}/></span><h3>{t("common.loadFailed")}</h3><p>{state.error}</p><button className="primary" onClick={state.reload}>{t("common.retry")}</button></div>;
  if (!state.data || (Array.isArray(state.data) && !state.data.length)) return <EmptyState title={empty ?? t("common.dataNotRegistered")} icon="folder"/>;
  return <>{children(state.data)}</>;
}

type DashboardData = {
  counters: Record<string, number>;
  riskDistribution: Array<{ riskLevel: string; _count: number }>;
  actionDistribution: Array<{ status: string; _count: number }>;
  recent: { fmeas: Array<{ id: string; title: string; code: string; status: string; updatedAt?: string }>; rulas: Array<{ id: string; title: string; score: number; actionLevel: number; updatedAt?: string }> };
};

const kpis: Record<string, { labelKey: string; captionKey: string; icon: IconName; tone: string; href: string }> = {
  projects: { labelKey: "dashboard.kpiProjects", captionKey: "dashboard.kpiProjectsCaption", icon: "projects", tone: "teal", href: "/projects" },
  fmeas: { labelKey: "dashboard.kpiFmea", captionKey: "dashboard.kpiFmeaCaption", icon: "fmea", tone: "blue", href: "/fmea" },
  rulas: { labelKey: "dashboard.kpiRula", captionKey: "dashboard.kpiRulaCaption", icon: "rula", tone: "violet", href: "/rula" },
  openActions: { labelKey: "dashboard.kpiOpenActions", captionKey: "dashboard.kpiOpenActionsCaption", icon: "actions", tone: "amber", href: "/actions" },
  overdueActions: { labelKey: "dashboard.kpiOverdueActions", captionKey: "dashboard.kpiOverdueActionsCaption", icon: "clock", tone: "orange", href: "/actions" },
  criticalItems: { labelKey: "dashboard.kpiCriticalItems", captionKey: "dashboard.kpiCriticalItemsCaption", icon: "warning", tone: "red", href: "/fmea" },
  members: { labelKey: "dashboard.kpiMembers", captionKey: "dashboard.kpiMembersCaption", icon: "members", tone: "teal", href: "/members" },
  knowledgeDocs: { labelKey: "dashboard.kpiKnowledge", captionKey: "dashboard.kpiKnowledgeCaption", icon: "knowledge", tone: "violet", href: "/knowledge" },
  pendingAI: { labelKey: "dashboard.kpiPendingAi", captionKey: "dashboard.kpiPendingAiCaption", icon: "assistant", tone: "blue", href: "/assistant" },
};
const subscriptionPlanKeys: Record<string, { title: string; description: string }> = {
  STARTER: { title: "registration.planStarter", description: "registration.planStarterDescription" },
  PROFESSIONAL: { title: "registration.planProfessional", description: "registration.planProfessionalDescription" },
  ENTERPRISE: { title: "registration.planEnterprise", description: "registration.planEnterpriseDescription" },
};
const riskColors: Record<string, string> = { LOW: "#2b9a6f", MEDIUM: "#e0a129", HIGH: "#e4772c", CRITICAL: "#d94f4f" };
const dashboardWidgetLabels: Record<string, string> = { "section:risk": "dashboard.riskDistribution", "section:actions": "dashboard.actionStatus", "section:recent": "dashboard.recent", "section:quick": "dashboard.quick", "kpi:projects": "dashboard.kpiProjects", "kpi:fmeas": "dashboard.kpiFmea", "kpi:rulas": "dashboard.kpiRula", "kpi:openActions": "dashboard.kpiOpenActions", "kpi:overdueActions": "dashboard.kpiOverdueActions", "kpi:criticalItems": "dashboard.kpiCriticalItems", "kpi:members": "dashboard.kpiMembers", "kpi:knowledgeDocs": "dashboard.kpiKnowledge", "kpi:pendingAI": "dashboard.kpiPendingAi" };
const defaultDashboardWidgetOrder = Object.keys(dashboardWidgetLabels);

function loadDashboardList(key: string, fallback: string[]) {
  try {
    const value = JSON.parse(localStorage.getItem(key) ?? "null") as unknown;
    return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : fallback;
  } catch { return fallback; }
}

function normalizeDashboardOrder(value: string[]) {
  const known = value.filter((item, index) => (dashboardWidgetLabels[item] || item.startsWith("kpi:")) && value.indexOf(item) === index);
  return [...known, ...defaultDashboardWidgetOrder.filter((item) => !known.includes(item))];
}

export function DashboardPage() {
  const state = useLoad<DashboardData>("/dashboard");
  const { locale, t } = useI18n();
  const numberLocale = locale === "en" ? "en-US" : "fa-IR";
  const [customizing, setCustomizing] = useState(false);
  const { session, orgId } = getSession();
  const widgetStorageKey = `nivasafe-dashboard-widgets:${session?.user.id ?? "guest"}:${orgId || "default"}`;
  const orderStorageKey = `${widgetStorageKey}:order`;
  const [hiddenWidgets, setHiddenWidgets] = useState<string[]>(() => loadDashboardList(widgetStorageKey, []));
  const [widgetOrder, setWidgetOrder] = useState<string[]>(() => normalizeDashboardOrder(loadDashboardList(orderStorageKey, defaultDashboardWidgetOrder)));
  const visibleWidget = (id: string) => !hiddenWidgets.includes(id);
  function toggleWidget(id: string) { setHiddenWidgets((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; localStorage.setItem(widgetStorageKey, JSON.stringify(next)); return next; }); }
  function moveWidgetTo(source: string, target: string) { setWidgetOrder((current) => { const next = [...current]; if (!next.includes(source)) next.push(source); if (!next.includes(target)) next.push(target); const from = next.indexOf(source); const to = next.indexOf(target); if (from < 0 || to < 0 || from === to) return current; next.splice(from, 1); next.splice(to, 0, source); localStorage.setItem(orderStorageKey, JSON.stringify(next)); return next; }); }
  function moveWidget(id: string, delta: -1 | 1, order = widgetOrder) { const index = order.indexOf(id); const target = order[index + delta]; if (target) moveWidgetTo(id, target); }
  function resetWidgets() { setHiddenWidgets([]); setWidgetOrder(defaultDashboardWidgetOrder); localStorage.removeItem(widgetStorageKey); localStorage.removeItem(orderStorageKey); }
  return <section className="page-shell">
    <PageHeader eyebrow={t("dashboard.eyebrow")} title={t("dashboard.title")} description={t("dashboard.description")} actions={<><button className="ghost" type="button" onClick={() => setCustomizing((value) => !value)}><Icon name="dashboard"/> {customizing ? t("dashboard.closeSettings") : t("dashboard.customize")}</button><Link className="primary button-link" to="/choose-path"><Icon name="plus"/> {t("dashboard.newAssessment")}</Link></>}/>
    <LoadState state={state}>{(data) => {
      const totalRisk = data.riskDistribution.reduce((sum, item) => sum + Number(item._count), 0) || 1;
      const recent = [
        ...data.recent.fmeas.map((item) => ({ type: "FMEA", title: item.title, meta: item.code, value: item.status, date: item.updatedAt, href: "/fmea" })),
        ...data.recent.rulas.map((item) => ({ type: "RULA", title: item.title, meta: t("assessment.actionLevel", { level: item.actionLevel }), value: `${t("assessment.score")} ${item.score}`, date: item.updatedAt, href: "/rula" })),
      ].slice(0, 6);
      const liveOrder = [...widgetOrder, ...Object.keys(data.counters).map((key) => `kpi:${key}`).filter((id) => !widgetOrder.includes(id))];
      function renderWidget(id: string): ReactNode {
        if (id.startsWith("kpi:")) {
          const key = id.slice(4); const value = data.counters[key]; if (value === undefined) return null;
          const item = kpis[key] ?? { labelKey: key, captionKey: "", icon: "chart" as IconName, tone: "teal", href: "/" };
          return <Link to={item.href} className={`kpi-card dashboard-widget dashboard-kpi-widget ${item.tone}`} key={id} data-widget-id={id}><span className="kpi-icon"><Icon name={item.icon}/></span><div className="kpi-copy"><small>{t(item.labelKey)}</small><strong>{value.toLocaleString(numberLocale)}</strong><span>{item.captionKey ? t(item.captionKey) : ""}</span></div><Icon name="arrow" size={18} className="kpi-arrow"/></Link>;
        }
        if (id === "section:risk") return <SectionCard key={id} title={t("dashboard.riskDistribution")} description={t("dashboard.riskDescription")} icon="chart" className="dashboard-widget dashboard-section-widget risk-panel">{!data.riskDistribution.length ? <EmptyState title={t("dashboard.noRisk")} description={t("dashboard.noRiskDescription")} icon="chart"/> : <div className="risk-bars">{data.riskDistribution.map((item) => <div className="risk-row" key={item.riskLevel}><div className="risk-row-head"><span><i style={{ background: riskColors[item.riskLevel] }}/><StatusBadge value={item.riskLevel}/></span><strong>{item._count.toLocaleString(numberLocale)}</strong></div><div className="progress-track"><span style={{ width: `${Math.max(6, (item._count / totalRisk) * 100)}%`, background: riskColors[item.riskLevel] }}/></div></div>)}</div>}</SectionCard>;
        if (id === "section:actions") return <SectionCard key={id} title={t("dashboard.actionStatus")} description={t("dashboard.actionDescription")} icon="actions" className="dashboard-widget dashboard-section-widget actions-panel">{!data.actionDistribution.length ? <EmptyState title={t("dashboard.noAction")} icon="actions"/> : <div className="action-summary">{data.actionDistribution.map((item) => <div className="summary-row" key={item.status}><StatusBadge value={item.status}/><strong>{item._count.toLocaleString(numberLocale)}</strong></div>)}</div>}<Link className="text-link" to="/actions">{t("dashboard.viewAllActions")} <Icon name="arrow" size={16}/></Link></SectionCard>;
        if (id === "section:recent") return <SectionCard key={id} title={t("dashboard.recent")} description={t("dashboard.recentDescription")} icon="activity" className="dashboard-widget dashboard-section-widget recent-panel">{!recent.length ? <EmptyState title={t("dashboard.noRecent")} icon="activity"/> : <div className="recent-list">{recent.map((item, index) => <Link to={item.href} className="recent-item" key={`${item.type}-${index}`}><span className={`recent-type ${item.type.toLowerCase()}`}>{item.type}</span><div><strong>{item.title}</strong><small>{item.meta}{item.date ? ` · ${formatDate(item.date)}` : ""}</small></div><span className="recent-value">{item.type === "FMEA" ? <StatusBadge value={item.value}/> : item.value}</span></Link>)}</div>}</SectionCard>;
        if (id === "section:quick") return <SectionCard key={id} title={t("dashboard.quick")} description={t("dashboard.quickDescription")} icon="sparkles" className="dashboard-widget dashboard-section-widget quick-panel"><div className="quick-actions"><Link to="/fmea"><Icon name="fmea"/><span><strong>{t("dashboard.newFmea")}</strong><small>{t("dashboard.processRisk")}</small></span></Link><Link to="/rula"><Icon name="rula"/><span><strong>{t("dashboard.newRula")}</strong><small>{t("dashboard.ergonomics")}</small></span></Link><Link to="/actions"><Icon name="actions"/><span><strong>{t("dashboard.correctiveAction")}</strong><small>{t("dashboard.actionTracking")}</small></span></Link><Link to="/assistant"><Icon name="assistant"/><span><strong>{t("dashboard.smartAssistant")}</strong><small>{t("dashboard.specialistGuide")}</small></span></Link></div></SectionCard>;
        return null;
      }
      return <>
        {customizing && <div className="dashboard-customizer"><div><strong>{t("dashboard.layout")}</strong><small>{t("dashboard.layoutDescription")}</small></div><div className="widget-checks">{liveOrder.map((id, index) => { const label = t(dashboardWidgetLabels[id] ?? id); return <div className="widget-control" key={id} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", id)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const source = event.dataTransfer.getData("text/plain"); if (source) moveWidgetTo(source, id); }}><label><input type="checkbox" checked={visibleWidget(id)} onChange={() => toggleWidget(id)}/><span>{label}</span></label><div className="widget-order-actions"><button type="button" className="icon-button" aria-label={t("dashboard.moveUp", { label })} title={t("dashboard.up")} disabled={index === 0} onClick={() => moveWidget(id, -1, liveOrder)}><Icon name="arrow" size={14} className="widget-arrow-up"/></button><button type="button" className="icon-button" aria-label={t("dashboard.moveDown", { label })} title={t("dashboard.down")} disabled={index === liveOrder.length - 1} onClick={() => moveWidget(id, 1, liveOrder)}><Icon name="arrow" size={14} className="widget-arrow-down"/></button></div></div>; })}</div><button type="button" className="text-button" onClick={resetWidgets}>{t("dashboard.resetWidgets")}</button></div>}
        <div className="dashboard-widgets">{liveOrder.filter(visibleWidget).map(renderWidget)}</div>
      </>;
    }}</LoadState>
  </section>;
}

type OrganizationDetails = { id: string; nameFa: string; nameEn: string; active?: boolean; nationalId?: string | null; industry?: string | null; employeeCount?: number | null; timezone?: string; defaultLocale?: string; riskMedium?: number; riskHigh?: number; riskCritical?: number; subscriptionPlan?: string; subscriptionStatus?: string; subscriptionProvider?: string; subscriptionStartedAt?: string; subscriptionExpiresAt?: string | null };
export function OrganizationsPage() {
  const current = useLoad<OrganizationDetails>("/organizations/current"); const organizations = useLoad<OrganizationDetails[]>("/organizations"); const dashboard = useLoad<DashboardData>("/dashboard");
  const { locale, t } = useI18n();
  const numberLocale = locale === "en" ? "en-US" : "fa-IR";
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const dialog = useDialog(); const role = getCurrentRole(); const canManage = ["SUPER_ADMIN", "ORG_ADMIN"].includes(role); const isSuperAdmin = role === "SUPER_ADMIN";
  const { session, orgId } = getSession();
  const editDraftKey = scopedDraftKey("organization-edit", session?.user.id, orgId);
  const createDraftKey = scopedDraftKey("organization-create", session?.user.id, orgId);
  const subscriptionDraftKey = scopedDraftKey("subscription-change", session?.user.id, orgId);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); try { await api("/organizations/current", { method: "PATCH", body: JSON.stringify({ nameFa: form.get("nameFa"), nameEn: form.get("nameEn"), nationalId: form.get("nationalId") || null, industry: form.get("industry") || null, employeeCount: form.get("employeeCount") ? Number(form.get("employeeCount")) : null }) }); await clearAutoSaveDraft(editDraftKey); current.reload(); organizations.reload(); setMessage(t("organization.infoSaved")); } catch (reason) { setError((reason as Error).message); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); try { const result = await api<OrganizationDetails>("/organizations", { method: "POST", body: JSON.stringify({ nameFa: form.get("nameFa"), nameEn: form.get("nameEn"), industry: form.get("industry") || null, employeeCount: form.get("employeeCount") ? Number(form.get("employeeCount")) : null, subscriptionPlan: form.get("subscriptionPlan") || "STARTER", defaultLocale: locale }) }); await clearAutoSaveDraft(createDraftKey); const session = getSession().session; if (session) saveSession({ ...session, organizations: [...session.organizations, { id: result.data.id, nameFa: result.data.nameFa, nameEn: result.data.nameEn, role: "ORG_ADMIN", active: result.data.active, subscriptionPlan: result.data.subscriptionPlan, subscriptionStatus: result.data.subscriptionStatus, subscriptionExpiresAt: result.data.subscriptionExpiresAt }] }, isSessionRemembered()); localStorage.setItem("nivasafe-org", result.data.id); event.currentTarget.reset(); organizations.reload(); current.reload(); setMessage(result.data.subscriptionStatus === "PENDING_PAYMENT" ? t("organization.createdPending") : t("organization.createdTrial")); } catch (reason) { setError((reason as Error).message); } }
  async function activateSubscription(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); try { const result = await api<OrganizationDetails>("/organizations/current/subscription/checkout", { method: "POST", body: JSON.stringify({ subscriptionPlan: form.get("subscriptionPlan") || "STARTER" }) }); await clearAutoSaveDraft(subscriptionDraftKey); const session = getSession().session; if (session) saveSession({ ...session, organizations: session.organizations.map((item) => item.id === result.data.id ? { ...item, subscriptionPlan: result.data.subscriptionPlan, subscriptionStatus: result.data.subscriptionStatus, subscriptionExpiresAt: result.data.subscriptionExpiresAt } : item) }, isSessionRemembered()); current.reload(); organizations.reload(); setMessage(t("organization.subscriptionUpdated")); } catch (reason) { setError((reason as Error).message); } }
  async function cancelSubscription() { if (!(await dialog.confirm(t("organization.cancelConfirm")))) return; setError(""); try { const result = await api<OrganizationDetails>("/organizations/current/subscription/cancel", { method: "POST" }); const session = getSession().session; if (session) saveSession({ ...session, organizations: session.organizations.map((item) => item.id === result.data.id ? { ...item, subscriptionStatus: result.data.subscriptionStatus, subscriptionExpiresAt: result.data.subscriptionExpiresAt } : item) }, isSessionRemembered()); current.reload(); organizations.reload(); setMessage(t("organization.subscriptionCanceled")); } catch (reason) { setError((reason as Error).message); } }
  async function setOrganizationActive(organization: OrganizationDetails) { const next = organization.active === false; const name = locale === "en" ? organization.nameEn : organization.nameFa; if (!(await dialog.confirm(t(next ? "organization.activateConfirm" : "organization.deactivateConfirm", { name })))) return; if (!(await dialog.confirm(t(next ? "organization.activateWarning" : "organization.deactivateWarning")))) return; try { await api(`/organizations/${organization.id}/status`, { method: "PATCH", body: JSON.stringify({ active: next, confirmation: next ? "ACTIVATE" : "DEACTIVATE" }) }); const session = getSession().session; if (session) saveSession({ ...session, organizations: session.organizations.map((item) => item.id === organization.id ? { ...item, active: next } : item) }, isSessionRemembered()); organizations.reload(); current.reload(); setMessage(next ? t("organization.activated") : t("organization.deactivated")); } catch (reason) { setError((reason as Error).message); } }
  async function deactivate() { if (!(await dialog.confirm(t("organization.deactivateRequest")))) return; if (!(await dialog.confirm(t("organization.deactivateRequestWarning")))) return; try { await api("/organizations/current/deactivate", { method: "POST" }); clearSession(); window.location.assign("/login"); } catch (reason) { setError((reason as Error).message); } }
  return <section className="page-shell"><PageHeader eyebrow={t("organization.management")} title={t("organization.title")} description={t("organization.description")}/>{error && <div className="alert error"><Icon name="warning"/>{error}</div>}{message && <div className="alert success"><Icon name="check"/>{message}</div>}
    <LoadState state={dashboard}>{(data) => <div className="kpi-grid crm-kpis">{Object.entries(data.counters).map(([key, value]) => { const item = kpis[key] ?? { labelKey: key, captionKey: "", icon: (key === "members" ? "members" : key === "knowledgeDocs" ? "knowledge" : "assistant") as IconName, tone: "teal", href: "/" }; return <div className={`kpi-card ${item.tone}`} key={key}><span className="kpi-icon"><Icon name={item.icon}/></span><div className="kpi-copy"><small>{t(item.labelKey)}</small><strong>{value.toLocaleString(numberLocale)}</strong><span>{item.captionKey ? t(item.captionKey) : ""}</span></div></div>; })}</div>}</LoadState>
    <LoadState state={current} empty={t("organization.noOther")}>{(organization) => { const planKeys = subscriptionPlanKeys[organization.subscriptionPlan ?? "STARTER"] ?? subscriptionPlanKeys.STARTER; const plan = t(planKeys.title); const planDescription = t(planKeys.description); const provider = organization.subscriptionProvider === "local" ? t("organization.localTrial") : organization.subscriptionProvider === "legacy" ? t("organization.existing") : organization.subscriptionProvider ?? t("organization.unregistered"); return <SectionCard title={t("organization.activeSubscription")} description={t("organization.subscriptionDescription")} icon="shield"><div className="subscription-panel"><div className="subscription-summary"><div><strong>{plan}</strong><small>{t("organization.provider")}: {provider}</small></div><StatusBadge value={organization.subscriptionStatus ?? "ACTIVE"}/><span className="subscription-expiry">{organization.subscriptionExpiresAt ? t("organization.until", { date: new Date(organization.subscriptionExpiresAt).toLocaleDateString(numberLocale) }) : t("organization.noExpiry")}</span></div>{canManage && <AutoSaveForm storageKey={subscriptionDraftKey} className="inline-form subscription-form" onSubmit={activateSubscription}><label>{t("organization.subscriptionPlan")}<select name="subscriptionPlan" defaultValue={organization.subscriptionPlan ?? "STARTER"}>{SUBSCRIPTION_PLANS.map((subscription) => { const keys = subscriptionPlanKeys[subscription.id] ?? subscriptionPlanKeys.STARTER; return <option key={subscription.id} value={subscription.id}>{t(keys.title)} — {t(keys.description)}</option>; })}</select></label><button className="primary"><Icon name="check"/> {t("organization.activateRenew")}</button>{isSubscriptionActive(organization.subscriptionStatus ?? "ACTIVE", organization.subscriptionExpiresAt) && <button className="ghost danger-button" type="button" onClick={() => void cancelSubscription()}>{t("organization.cancelSubscription")}</button>}</AutoSaveForm>}<small className="field-hint">{t("organization.paymentNote")}</small></div></SectionCard>; }}</LoadState>
    {canManage && <div className="form-panels"><SectionCard title={t("organization.activeInfo")} description={t("organization.editDescription")} icon="projects"><LoadState state={current} empty={t("organization.noOther")}>{(organization) => <AutoSaveForm storageKey={editDraftKey} className="form-grid" onSubmit={save}><label>{t("organization.namePersian")}<input name="nameFa" defaultValue={organization.nameFa} required/></label><label>{t("organization.nameEnglish")}<input name="nameEn" defaultValue={organization.nameEn} required dir="ltr"/></label><label>{t("organization.nationalId")}<input name="nationalId" defaultValue={organization.nationalId ?? ""}/></label><label>{t("organization.industry")}<input name="industry" defaultValue={organization.industry ?? ""}/></label><label>{t("organization.employees")}<input name="employeeCount" type="number" min="0" defaultValue={organization.employeeCount ?? ""}/></label><button className="primary full"><Icon name="check"/> {t("organization.saveInfo")}</button></AutoSaveForm>}</LoadState></SectionCard><SectionCard title={t("organization.createNew")} description={t("organization.createDescription")} icon="plus"><AutoSaveForm storageKey={createDraftKey} className="form-grid" onSubmit={create}><label>{t("organization.namePersian")}<input name="nameFa" required/></label><label>{t("organization.nameEnglish")}<input name="nameEn" required dir="ltr"/></label><label>{t("organization.industry")}<input name="industry"/></label><label>{t("organization.employees")}<input name="employeeCount" type="number" min="0"/></label><label className="full">{t("organization.subscriptionPlan")}<select name="subscriptionPlan" defaultValue="STARTER">{SUBSCRIPTION_PLANS.map((subscription) => { const keys = subscriptionPlanKeys[subscription.id] ?? subscriptionPlanKeys.STARTER; return <option key={subscription.id} value={subscription.id}>{t(keys.title)} — {t(keys.description)}</option>; })}</select></label><button className="primary full"><Icon name="plus"/> {t("organization.createSeparate")}</button></AutoSaveForm></SectionCard></div>}
    <SectionCard title={t("organization.available")} description={`${(organizations.data?.length ?? 0).toLocaleString(numberLocale)} ${t("organization.availableDescription")}`} icon="members"><LoadState state={organizations} empty={t("organization.noOther")}>{(data) => <div className="simple-list">{data.map((organization) => { const name = locale === "en" ? organization.nameEn : organization.nameFa; return <div className="simple-list-row" key={organization.id}><div><strong>{name}</strong><small>{organization.industry || t("organization.unregisteredIndustry")} · {organization.employeeCount ? `${organization.employeeCount.toLocaleString(numberLocale)} ${t("common.people")}` : t("organization.unregisteredEmployees")}</small></div><div className="organization-row-actions"><StatusBadge value={organization.subscriptionStatus ?? "ACTIVE"}/><span className={`organization-status ${organization.active === false ? "inactive" : "active"}`}>{organization.active === false ? t("members.inactive") : t("members.active")}</span><button className="text-button" type="button" onClick={() => { localStorage.setItem("nivasafe-org", organization.id); window.location.assign("/"); }}>{organization.id === current.data?.id ? t("organization.enterCompany") : t("organization.enter")}</button>{isSuperAdmin && <button className="text-button" type="button" onClick={() => void setOrganizationActive(organization)}>{organization.active === false ? t("organization.activate") : t("organization.deactivate")}</button>}</div></div>; })}</div>}</LoadState></SectionCard>
    {canManage && !isSuperAdmin && <button className="ghost danger-button" onClick={() => void deactivate()}>{t("organization.deactivateActive")}</button>}
  </section>;
}

type Project = { id: string; name: string; code: string; status: string; description?: string; updatedAt?: string };
type Process = { id: string; projectId: string; name: string };
type Activity = { id: string; projectId: string; processId?: string; title: string; location?: string };

export function ProjectsPage() {
  const projects = useLoad<Project[]>("/projects");
  const processes = useLoad<Process[]>("/processes");
  const activities = useLoad<Activity[]>("/activities");
  const { locale, t } = useI18n();
  const numberLocale = locale === "en" ? "en-US" : "fa-IR";
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const dialog = useDialog();
  const canManage = ["SUPER_ADMIN", "ORG_ADMIN", "HSE_MANAGER"].includes(getCurrentRole());
  const { session, orgId } = getSession();
  const projectDraftKey = scopedDraftKey("project-create", session?.user.id, orgId);
  const processDraftKey = scopedDraftKey("process-create", session?.user.id, orgId);
  const activityDraftKey = scopedDraftKey("activity-create", session?.user.id, orgId);
  async function create(path: string, event: FormEvent<HTMLFormElement>, reload: () => void, message: string, draftKey: string) {
    event.preventDefault(); setError(""); setSuccess("");
    const form = event.currentTarget;
    const payload = Object.fromEntries(new FormData(form));
    for (const [key, value] of Object.entries(payload)) if (value === "") delete payload[key];
    try { await api(path, { method: "POST", body: JSON.stringify(payload) }); await clearAutoSaveDraft(draftKey); form.reset(); reload(); setSuccess(message); }
    catch (reason) { setError((reason as Error).message); }
  }
  async function rename(path: string, id: string, current: string, reload: () => void) { const name = (await dialog.prompt(t("projects.newName"), current))?.trim(); if (!name || name === current) return; try { await api(`${path}/${id}`, { method: "PATCH", body: JSON.stringify(path === "/activities" ? { title: name } : { name }) }); reload(); setSuccess(t("projects.changesSaved")); } catch (reason) { setError((reason as Error).message); } }
  async function remove(path: string, id: string, label: string, reload: () => void) { if (!(await dialog.confirm(t("projects.deleteConfirm", { name: label })))) return; try { await api(`${path}/${id}`, { method: "DELETE" }); reload(); setSuccess(t("projects.itemDeleted")); } catch (reason) { setError((reason as Error).message); } }
  const counts = { projects: projects.data?.length ?? 0, processes: processes.data?.length ?? 0, activities: activities.data?.length ?? 0 };
  return <section className="page-shell">
    <PageHeader eyebrow={t("projects.eyebrow")} title={t("projects.title")} description={t("projects.description")}/>
    {error && <div className="alert error"><Icon name="warning"/>{error}</div>}{success && <div className="alert success"><Icon name="check"/>{success}</div>}
    <div className="mini-stats"><div><Icon name="projects"/><strong>{counts.projects.toLocaleString(numberLocale)}</strong><span>{t("projects.project")}</span></div><div><Icon name="activity"/><strong>{counts.processes.toLocaleString(numberLocale)}</strong><span>{t("projects.process")}</span></div><div><Icon name="folder"/><strong>{counts.activities.toLocaleString(numberLocale)}</strong><span>{t("projects.activity")}</span></div></div>
    {canManage && <div className="form-panels">
      <SectionCard title={t("projects.newProject")} description={t("projects.projectDescription")} icon="projects">
        <AutoSaveForm storageKey={projectDraftKey} className="form-grid" onSubmit={(event) => create("/projects", event, projects.reload, t("projects.projectCreated"), projectDraftKey)}>
          <label>{t("projects.projectName")}<input name="name" placeholder={t("projects.projectNamePlaceholder")} required/></label><label>{t("projects.uniqueCode")}<input name="code" placeholder={t("projects.codePlaceholder")} required/></label><label className="full">{t("common.description")}<textarea name="description" rows={3} placeholder={t("projects.projectDetailsPlaceholder")}/></label><button className="primary full"><Icon name="plus"/> {t("projects.createProject")}</button>
        </AutoSaveForm>
      </SectionCard>
      <SectionCard title={t("projects.newProcess")} description={t("projects.processDescription")} icon="activity">
        <AutoSaveForm storageKey={processDraftKey} className="form-grid" onSubmit={(event) => create("/processes", event, processes.reload, t("projects.processCreated"), processDraftKey)}>
          <label className="full">{t("projects.project")}<select name="projectId" required><option value="">{t("assessment.projectSelect")}</option>{projects.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="full">{t("projects.processName")}<input name="name" placeholder={t("projects.processNamePlaceholder")} required/></label><label className="full">{t("common.description")}<textarea name="description" rows={3} placeholder={t("projects.processDetailsPlaceholder")}/></label><button className="primary full"><Icon name="plus"/> {t("projects.createProcess")}</button>
        </AutoSaveForm>
      </SectionCard>
    </div>}
    {canManage && <SectionCard title={t("projects.registerActivity")} description={t("projects.activityDescription")} icon="plus">
      <AutoSaveForm storageKey={activityDraftKey} className="inline-form" onSubmit={(event) => create("/activities", event, activities.reload, t("projects.activityCreated"), activityDraftKey)}>
        <label>{t("projects.project")}<select name="projectId" required><option value="">{t("assessment.projectSelect")}</option>{projects.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t("projects.process")}<select name="processId"><option value="">{t("projects.noProcess")}</option>{processes.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t("projects.activityTitle")}<input name="title" placeholder={t("projects.activityTitle")} required/></label><label>{t("projects.location")}<input name="location" placeholder={t("projects.locationPlaceholder")}/></label><button className="primary"><Icon name="plus"/> {t("projects.registerActivityButton")}</button>
      </AutoSaveForm>
    </SectionCard>}
    <SectionCard title={t("projects.projectList")} description={t("projects.listDescription")} icon="folder">
      <LoadState state={projects} empty={t("projects.noProject")}>{(data) => <div className="project-cards">{data.map((project) => {
        const processCount = processes.data?.filter((x) => x.projectId === project.id).length ?? 0;
        const activityCount = activities.data?.filter((x) => x.projectId === project.id).length ?? 0;
        return <article className="project-card" key={project.id}><div className="project-top"><span className="project-code">{project.code}</span><StatusBadge value={project.status}/></div><h3>{project.name}</h3><p>{project.description || t("projects.noDescription")}</p><div className="project-meta"><span><Icon name="activity" size={16}/>{processCount.toLocaleString(numberLocale)} {t("projects.processCount")}</span><span><Icon name="folder" size={16}/>{activityCount.toLocaleString(numberLocale)} {t("projects.activityCount")}</span></div>{canManage && <div className="card-actions"><span onClick={() => void rename("/projects", project.id, project.name, projects.reload)}><Icon name="activity" size={15}/> {t("common.edit")}</span><span className="danger-link" onClick={() => void remove("/projects", project.id, `${t("projects.project")} «${project.name}»`, projects.reload)}><Icon name="trash" size={15}/> {t("common.delete")}</span></div>}</article>;
      })}</div>}</LoadState>
    </SectionCard>
    {canManage && <div className="form-panels"><SectionCard title={t("projects.processList")} description={t("projects.processListDescription")} icon="activity"><LoadState state={processes} empty={t("projects.noProcessRegistered")}>{(data) => <div className="simple-list">{data.map((item) => <div className="simple-list-row" key={item.id}><div><strong>{item.name}</strong><small>{projects.data?.find((project) => project.id === item.projectId)?.name ?? t("projects.unknownProject")}</small></div><div className="card-actions"><span onClick={() => void rename("/processes", item.id, item.name, processes.reload)}>{t("common.edit")}</span><span className="danger-link" onClick={() => void remove("/processes", item.id, `${t("projects.process")} «${item.name}»`, processes.reload)}>{t("common.delete")}</span></div></div>)}</div>}</LoadState></SectionCard><SectionCard title={t("projects.activityList")} description={t("projects.activityListDescription")} icon="folder"><LoadState state={activities} empty={t("projects.noActivity")}>{(data) => <div className="simple-list">{data.map((item) => <div className="simple-list-row" key={item.id}><div><strong>{item.title}</strong><small>{item.location || t("projects.unknownLocation")}</small></div><div className="card-actions"><span onClick={() => void rename("/activities", item.id, item.title, activities.reload)}>{t("common.edit")}</span><span className="danger-link" onClick={() => void remove("/activities", item.id, `${t("projects.activity")} «${item.title}»`, activities.reload)}>{t("common.delete")}</span></div></div>)}</div>}</LoadState></SectionCard></div>}
  </section>;
}

type Action = { id: string; title: string; description?: string; priority: string; status: string; progress: number; dueDate?: string; assigneeName?: string };
export function ActionsPage() {
  const state = useLoad<Action[]>("/actions");
  const projects = useLoad<Project[]>("/projects");
  const { locale, t } = useI18n();
  const numberLocale = locale === "en" ? "en-US" : "fa-IR";
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const canEditActions = ["SUPER_ADMIN", "ORG_ADMIN", "HSE_MANAGER", "ASSESSOR"].includes(getCurrentRole());
  const { session, orgId } = getSession();
  const actionDraftKey = scopedDraftKey("action-create", session?.user.id, orgId);
  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setError("");
    try { await api("/actions", { method: "POST", body: JSON.stringify({ projectId: form.get("projectId"), title: form.get("title"), description: form.get("description"), priority: form.get("priority"), assigneeName: form.get("assigneeName") || null, dueDate: form.get("dueDate") || null }) }); await clearAutoSaveDraft(actionDraftKey); formElement.reset(); state.reload(); setMessage(t("actions.created")); }
    catch (reason) { setError((reason as Error).message); }
  }
  const openCount = state.data?.filter((x) => !["COMPLETED", "CANCELLED"].includes(x.status)).length ?? 0;
  const doneCount = state.data?.filter((x) => x.status === "COMPLETED").length ?? 0;
  return <section className="page-shell">
    <PageHeader eyebrow={t("actions.eyebrow")} title={t("actions.title")} description={t("actions.description")}/>
    {error && <div className="alert error"><Icon name="warning"/>{error}</div>}{message && <div className="alert success"><Icon name="check"/>{message}</div>}
    <div className="mini-stats"><div><Icon name="actions"/><strong>{openCount.toLocaleString(numberLocale)}</strong><span>{t("actions.open")}</span></div><div><Icon name="check"/><strong>{doneCount.toLocaleString(numberLocale)}</strong><span>{t("actions.completed")}</span></div><div><Icon name="chart"/><strong>{state.data?.length ? Math.round(state.data.reduce((s, x) => s + x.progress, 0) / state.data.length).toLocaleString(numberLocale) : (0).toLocaleString(numberLocale)}%</strong><span>{t("actions.averageProgress")}</span></div></div>
    {canEditActions && <SectionCard title={t("actions.new")} description={t("actions.newDescription")} icon="plus">
      <AutoSaveForm storageKey={actionDraftKey} className="action-form" onSubmit={create}><label>{t("projects.project")}<select name="projectId" required><option value="">{t("assessment.projectSelect")}</option>{projects.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t("actions.titleLabel")}<input name="title" placeholder={t("actions.titlePlaceholder")} required/></label><label className="wide">{t("actions.detailsLabel")}<input name="description" placeholder={t("actions.detailsPlaceholder")} required/></label><label>{t("actions.priority")}<select name="priority"><option value="MEDIUM">{t("status.medium")}</option><option value="HIGH">{t("status.high")}</option><option value="CRITICAL">{t("status.critical")}</option><option value="LOW">{t("status.low")}</option></select></label><label>{t("actions.assignee")}<input name="assigneeName" placeholder={t("actions.assigneePlaceholder")}/></label><label>{t("actions.dueDate")}<input name="dueDate" type="date"/></label><button className="primary"><Icon name="plus"/> {t("actions.register")}</button></AutoSaveForm>
    </SectionCard>}
    <SectionCard title={t("actions.list")} description={t("actions.listDescription")} icon="actions">
      <LoadState state={state} empty={t("actions.noAction")}>{(data) => <div className="table-wrap"><table><thead><tr><th>{t("actions.action")}</th><th>{t("actions.priorityColumn")}</th><th>{t("actions.statusColumn")}</th><th>{t("actions.progress")}</th><th>{t("actions.assigneeColumn")}</th><th>{t("actions.dueDateColumn")}</th></tr></thead><tbody>{data.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.description}</small></td><td><StatusBadge value={item.priority}/></td><td>{canEditActions ? <select className="compact-select" value={item.status} onChange={async (event) => { try { setError(""); await api(`/actions/${item.id}`, { method: "PATCH", body: JSON.stringify({ status: event.target.value }) }); state.reload(); } catch (reason) { setError((reason as Error).message); } }}><option value="OPEN">{t("status.open")}</option><option value="IN_PROGRESS">{t("status.inProgress")}</option><option value="WAITING_FOR_REVIEW">{t("status.waitingForReview")}</option><option value="COMPLETED">{t("status.completed")}</option><option value="REJECTED">{t("status.rejected")}</option></select> : <StatusBadge value={item.status}/>}</td><td><div className="table-progress"><div><span style={{ width: `${item.progress}%` }}/></div><b>{item.progress.toLocaleString(numberLocale)}%</b></div></td><td>{item.assigneeName ?? t("common.none")}</td><td>{formatDate(item.dueDate)}</td></tr>)}</tbody></table></div>}</LoadState>
    </SectionCard>
  </section>;
}

type KnowledgeAttachment = { id: string; originalName: string; mimeType: string; size: number; kind: string; createdAt: string; downloadPath: string };
type Knowledge = { id: string; title: string; content: string; tags: string[]; published?: boolean; aiReadable?: boolean; aiOnly?: boolean; isGlobal?: boolean; visibility?: string; visibleUserIds?: string[] | null; visibleOrganizationIds?: string[] | null; version?: number; updatedAt?: string; attachments?: KnowledgeAttachment[] };
type KnowledgeMember = { user: { id: string; displayName: string; email: string }; role: string; active: boolean };
type KnowledgeOrganization = { id: string; nameFa: string; nameEn: string; subscriptionPlan?: string; subscriptionStatus?: string };
type KnowledgeQuota = { plan: string; tokenLimit: number; usedTokens: number; remainingTokens: number; maxFileBytes: number; maxFileSizeLabel: string; canUpload: boolean };
const knowledgeFileSize = (size: number) => size > 1024 * 1024 ? `${(size / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.ceil(size / 1024))} KB`;
export function KnowledgePage() {
  const state = useLoad<Knowledge[]>("/knowledge");
  const quota = useLoad<KnowledgeQuota>("/knowledge/quota");
  const { locale, t } = useI18n();
  const numberLocale = locale === "en" ? "en-US" : "fa-IR";
  const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const dialog = useDialog();
  const role = getCurrentRole(); const canManageKnowledge = ["SUPER_ADMIN", "ORG_ADMIN", "HSE_MANAGER"].includes(role); const canManageGlobal = role === "SUPER_ADMIN";
  const { session, orgId } = getSession();
  const knowledgeDraftKey = scopedDraftKey("knowledge-create", session?.user.id, orgId);
  const members = useLoad<KnowledgeMember[]>(canManageKnowledge ? "/members" : null);
  const organizations = useLoad<KnowledgeOrganization[]>(canManageGlobal ? "/organizations" : null);
  const filtered = useMemo(() => (state.data ?? []).filter((item) => `${item.title} ${item.content} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [state.data, query]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); let created: Knowledge | null = null; setError(""); setMessage(""); try { const visibility = String(form.get("visibility") || "ALL"); const aiOnly = form.get("aiOnly") === "on"; const isGlobal = canManageGlobal && form.get("isGlobal") === "on"; created = (await api<Knowledge>("/knowledge", { method: "POST", body: JSON.stringify({ title: form.get("title"), content: form.get("content"), tags: String(form.get("tags") || "").split(",").map((x) => x.trim()).filter(Boolean), published: !aiOnly && form.get("published") === "on", aiReadable: form.get("aiReadable") === "on", aiOnly, isGlobal, visibility, visibleUserIds: visibility === "SELECTED" ? form.getAll("visibleUserIds").map(String) : [], visibleOrganizationIds: isGlobal ? form.getAll("visibleOrganizationIds").map(String) : [] }) })).data; const file = form.get("file"); if (file instanceof File && file.size > 0) { const upload = new FormData(); upload.append("file", file); await api(`/knowledge/${created.id}/attachments`, { method: "POST", body: upload }); } await clearAutoSaveDraft(knowledgeDraftKey); element.reset(); state.reload(); quota.reload(); setMessage(t("knowledge.created")); } catch (reason) { if (created) await api(`/knowledge/${created.id}`, { method: "DELETE" }).catch(() => undefined); setError((reason as Error).message); } }
  async function edit(item: Knowledge) { const title = (await dialog.prompt(t("assessment.editTitle"), item.title))?.trim(); if (!title || title === item.title) return; try { await api(`/knowledge/${item.id}`, { method: "PATCH", body: JSON.stringify({ title }) }); state.reload(); setMessage(t("knowledge.documentEdited")); } catch (reason) { setError((reason as Error).message); } }
  async function togglePublished(item: Knowledge) { try { await api(`/knowledge/${item.id}`, { method: "PATCH", body: JSON.stringify({ published: item.published === false }) }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function toggleAiOnly(item: Knowledge) { try { await api(`/knowledge/${item.id}`, { method: "PATCH", body: JSON.stringify({ aiOnly: !item.aiOnly, published: item.aiOnly ? true : false }) }); state.reload(); setMessage(item.aiOnly ? t("knowledge.documentPublished") : t("knowledge.documentAiOnly")); } catch (reason) { setError((reason as Error).message); } }
  async function toggleAiReadable(item: Knowledge) { if (item.aiOnly && item.aiReadable !== false) return; try { await api(`/knowledge/${item.id}`, { method: "PATCH", body: JSON.stringify({ aiReadable: item.aiReadable === false }) }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function remove(item: Knowledge) { if (!(await dialog.confirm(`${t("common.delete")} «${item.title}»؟`))) return; try { await api(`/knowledge/${item.id}`, { method: "DELETE" }); state.reload(); quota.reload(); setMessage(t("common.delete")); } catch (reason) { setError((reason as Error).message); } }
  async function removeAttachment(item: KnowledgeAttachment) { if (!(await dialog.confirm(`${t("common.delete")} «${item.originalName}»؟`))) return; try { await api(`/knowledge/attachments/${item.id}`, { method: "DELETE" }); state.reload(); quota.reload(); setMessage(t("knowledge.attachmentDeleted")); } catch (reason) { setError((reason as Error).message); } }
  async function downloadAttachment(item: KnowledgeAttachment) { try { const blob = await download(item.downloadPath); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = item.originalName; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { setError((reason as Error).message); } }
  return <section className="page-shell">
    <PageHeader eyebrow={t("knowledge.eyebrow")} title={t("knowledge.title")} description={t("knowledge.description")} actions={<div className="search-box"><Icon name="search"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t("knowledge.searchPlaceholder")}/></div>}/>
    {error && <div className="alert error"><Icon name="warning"/>{error}</div>}{message && <div className="alert success"><Icon name="check"/>{message}</div>}
    {quota.data && <div className="knowledge-quota"><span><Icon name="assistant"/> {t("knowledge.tokenUsage")}: <strong>{quota.data.usedTokens.toLocaleString(numberLocale)}</strong> {t("common.of")} {quota.data.tokenLimit.toLocaleString(numberLocale)}</span><span>{t("knowledge.remaining")}: <strong>{quota.data.remainingTokens.toLocaleString(numberLocale)}</strong> · {t("knowledge.maxFile")} {quota.data.maxFileSizeLabel}</span></div>}
    {canManageKnowledge && <SectionCard title={t("knowledge.new")} description={t("knowledge.newDescription")} icon="plus">
      <AutoSaveForm storageKey={knowledgeDraftKey} className="knowledge-form" onSubmit={create}>
        <div className="knowledge-form-top"><label>{t("knowledge.documentTitle")}<input name="title" placeholder={t("knowledge.documentTitlePlaceholder")} required/></label><label>{t("knowledge.tags")}<input name="tags" placeholder={t("knowledge.tagsPlaceholder")}/></label></div>
        <label className="knowledge-content-field">{t("knowledge.content")}<textarea name="content" rows={7} placeholder={t("knowledge.contentPlaceholder")}/></label>
        <div className="knowledge-options"><label>{t("knowledge.visibility")}<select name="visibility" defaultValue="ALL"><option value="ALL">{t("knowledge.allUsers")}</option><option value="SELECTED">{t("knowledge.selectedUsers")}</option><option value="HIDDEN">{t("knowledge.hiddenUsers")}</option></select></label><label className="knowledge-user-select">{t("knowledge.selectedUsersLabel")}<select name="visibleUserIds" multiple size={Math.min(4, Math.max(2, members.data?.length ?? 2))}>{members.data?.filter((member) => member.active).map((member) => <option key={member.user.id} value={member.user.id}>{member.user.displayName} · {member.user.email}</option>)}</select><small>{t("knowledge.multiSelectHint")}</small></label>{canManageGlobal && <label className="knowledge-user-select">{t("knowledge.globalOrganizations")}<select name="visibleOrganizationIds" multiple size={Math.min(4, Math.max(2, organizations.data?.length ?? 2))}>{organizations.data?.map((organization) => <option key={organization.id} value={organization.id}>{locale === "en" ? organization.nameEn : organization.nameFa}</option>)}</select><small>{t("knowledge.emptyAllHint")}</small></label>}<label className="checkbox-card"><input name="published" type="checkbox" defaultChecked/><span><strong>{t("knowledge.visibleToUsers")}</strong><small>{t("knowledge.visibleToUsersHint")}</small></span></label><label className="checkbox-card"><input name="aiReadable" type="checkbox" defaultChecked/><span><strong>{t("knowledge.aiReadable")}</strong><small>{t("knowledge.aiReadableHint")}</small></span></label><label className="checkbox-card"><input name="aiOnly" type="checkbox"/><span><strong>{t("knowledge.aiOnly")}</strong><small>{t("knowledge.aiOnlyHint")}</small></span></label>{canManageGlobal && <label className="checkbox-card"><input name="isGlobal" type="checkbox"/><span><strong>{t("knowledge.globalDefault")}</strong><small>{t("knowledge.globalDefaultHint")}</small></span></label>}<label className="knowledge-file"><span>{t("knowledge.attachment")}</span><input name="file" type="file" disabled={quota.data?.canUpload === false} accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx,.xlsx,.csv,.txt"/><small>{t("knowledge.quotaHint", { size: quota.data?.maxFileSizeLabel ?? (locale === "en" ? "5 MB" : "۵ MB") })}</small></label></div>
        <div className="knowledge-form-footer"><span className="knowledge-form-note"><Icon name="assistant" size={17}/> {t("knowledge.registerNote")}</span><button className="primary knowledge-submit"><Icon name="plus"/> {t("knowledge.register")}</button></div>
      </AutoSaveForm>
    </SectionCard>}
    <SectionCard title={t("knowledge.visibleDocuments")} description={`${filtered.length.toLocaleString(numberLocale)} ${t("knowledge.visibleCount")}`} icon="knowledge">
      {!filtered.length ? <EmptyState title={t("knowledge.noSearchResult")} description={t("knowledge.noSearchResultDescription")} icon="search"/> : <div className="knowledge-grid">{filtered.map((item) => { const canEdit = canManageKnowledge && (!item.isGlobal || canManageGlobal); return <article className="knowledge-card" key={item.id}><div className="doc-icon"><Icon name="knowledge"/></div><div><div className="knowledge-title-row"><h3>{item.title}</h3><div className="knowledge-badges">{item.isGlobal && <span className="tag">{item.visibleOrganizationIds?.length ? t("common.selectedCompanies") : t("common.defaultAllCompanies")}</span>}{item.aiOnly && <span className="tag">{t("common.aiOnly")}</span>}{item.published === false && <StatusBadge value="DRAFT"/>}{item.aiReadable === false && <span className="tag">{t("common.humanOnly")}</span>}</div></div><p>{item.content || t("knowledge.fileOnly")}</p><div className="tag-row">{item.tags.map((tag) => <span className="tag" key={tag}>#{tag}</span>)}{item.visibility && item.visibility !== "ALL" && <span className="tag">{item.visibility === "SELECTED" ? t("common.selected") : t("common.hidden")}</span>}</div>{item.attachments?.length ? <div className="knowledge-attachments">{item.attachments.map((file) => <div className="knowledge-attachment" key={file.id}><Icon name="files" size={15}/><span title={file.originalName}>{file.originalName} · {knowledgeFileSize(file.size)}</span><button className="icon-button" title={t("common.download")} onClick={() => void downloadAttachment(file)}><Icon name="download" size={14}/></button>{canEdit && <button className="icon-button danger" title={t("common.delete")} onClick={() => void removeAttachment(file)}><Icon name="trash" size={14}/></button>}</div>)}</div> : null}{item.updatedAt && <small>{t("knowledge.updated")}: {formatDate(item.updatedAt)} · {t("common.version")} {item.version ?? 1}</small>}{canEdit && <div className="knowledge-actions"><button className="text-button" onClick={() => void edit(item)}>{t("common.edit")}</button>{!item.aiOnly && <button className="text-button" onClick={() => void togglePublished(item)}>{item.published === false ? t("knowledge.published") : t("knowledge.hide")}</button>}{(!item.aiOnly || item.aiReadable === false) && <button className="text-button" onClick={() => void toggleAiReadable(item)}>{item.aiReadable === false ? t("knowledge.enableAi") : t("knowledge.disableAi")}</button>}{canManageGlobal && <button className="text-button" onClick={() => void toggleAiOnly(item)}>{item.aiOnly ? t("knowledge.humanView") : t("common.aiOnly")}</button>}<button className="text-button danger-link" onClick={() => void remove(item)}>{t("common.delete")}</button></div>}</div></article>; })}</div>}
    </SectionCard>
  </section>;
}

type Notification = { id: string; title: string; message: string; readAt?: string; createdAt: string };
type NotificationPreferences = { emailEnabled: boolean; pushEnabled: boolean; riskAlerts: boolean; dueReminders: boolean };
export function NotificationsPage() {
  const state = useLoad<Notification[]>("/notifications"); const preferences = useLoad<NotificationPreferences>("/notifications/preferences"); const unread = state.data?.filter((x) => !x.readAt).length ?? 0; const [error, setError] = useState("");
  const { locale, t } = useI18n();
  const numberLocale = locale === "en" ? "en-US" : "fa-IR";
  async function markOne(id: string) { try { setError(""); await api(`/notifications/${id}/read`, { method: "PATCH" }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function markAll() { try { setError(""); await api("/notifications/read-all", { method: "POST" }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function togglePreference(key: keyof NotificationPreferences, value: boolean) { try { setError(""); await api("/notifications/preferences", { method: "PATCH", body: JSON.stringify({ [key]: value }) }); preferences.reload(); } catch (reason) { setError((reason as Error).message); } }
  const preferenceData = preferences.data;
  return <section className="page-shell"><PageHeader eyebrow={t("notifications.eyebrow")} title={t("notifications.title")} description={`${unread.toLocaleString(numberLocale)} ${t("notifications.unread")}`} actions={<button className="ghost" disabled={!unread} onClick={() => void markAll()}><Icon name="check"/> {t("notifications.readAll")}</button>}/>
     {error && <div className="alert error"><Icon name="warning"/>{error}</div>}
     {preferenceData && <SectionCard title={t("notifications.settings")} description={t("notifications.settingsDescription")} icon="notifications"><div className="preference-grid">{([ ["emailEnabled", "notifications.email", "notifications.emailDescription"], ["pushEnabled", "notifications.browser", "notifications.browserDescription"], ["riskAlerts", "notifications.risk", "notifications.riskDescription"], ["dueReminders", "notifications.due", "notifications.dueDescription"] ] as const).map(([key, labelKey, descriptionKey]) => <label className="checkbox-card" key={key}><input type="checkbox" checked={preferenceData[key]} onChange={(event) => void togglePreference(key, event.target.checked)}/><span><strong>{t(labelKey)}</strong><small>{t(descriptionKey)}</small></span></label>)}</div></SectionCard>}
     <LoadState state={state} empty={t("notifications.none")}>{(data) => <div className="notification-list">{data.map((item) => <article className={`notification-card ${item.readAt ? "read" : "unread"}`} key={item.id}><span className="notification-icon"><Icon name={item.title.includes("بحرانی") || item.title.toLowerCase().includes("critical") ? "warning" : "notifications"}/></span><div><div className="notification-title"><h3>{item.title}</h3>{!item.readAt && <span>{t("notifications.new")}</span>}</div><p>{item.message}</p><small>{formatDate(item.createdAt, true)}</small></div>{!item.readAt && <button className="icon-button" title={t("notifications.markRead")} onClick={() => void markOne(item.id)}><Icon name="check"/></button>}</article>)}</div>}</LoadState>
  </section>;
}

type Audit = { id: string; action: string; entityType?: string; entityId?: string; createdAt: string; user?: { displayName: string; email?: string } };
export function AuditPage() {
  const state = useLoad<Audit[]>("/audit");
  const { t } = useI18n();
  return <section className="page-shell"><PageHeader eyebrow={t("audit.eyebrow")} title={t("audit.title")} description={t("audit.description")}/>
    <SectionCard title={t("audit.report")} icon="audit"><LoadState state={state} empty={t("audit.none")}>{(data) => <div className="table-wrap"><table><thead><tr><th>{t("audit.time")}</th><th>{t("audit.user")}</th><th>{t("audit.event")}</th><th>{t("audit.entity")}</th></tr></thead><tbody>{data.map((item) => <tr key={item.id}><td>{formatDate(item.createdAt, true)}</td><td><strong>{item.user?.displayName ?? t("common.system")}</strong><small>{item.user?.email}</small></td><td><code className="event-code">{item.action}</code></td><td>{item.entityType ? `${item.entityType} · ${item.entityId ?? t("common.none")}` : t("common.none")}</td></tr>)}</tbody></table></div>}</LoadState></SectionCard>
  </section>;
}

export function HealthPage() {
  const state = useLoad<Record<string, string>>("/health");
  const { t } = useI18n();
  const label: Record<string, string> = { status: "health.status", database: "health.database", redis: "health.redis", storage: "health.storage", ai: "health.ai" };
  const description: Record<string, string> = { status: "health.statusDescription", database: "health.databaseDescription", redis: "health.redisDescription", storage: "health.storageDescription", ai: "health.aiDescription" };
  return <section className="page-shell"><PageHeader eyebrow={t("health.eyebrow")} title={t("health.title")} description={t("health.description")} actions={<button className="ghost" onClick={state.reload}><Icon name="activity"/> {t("health.refresh")}</button>}/>
    <LoadState state={state}>{(data) => <div className="health-grid">{Object.entries(data).map(([key, value]) => { const good = !["down", "unhealthy", "failed"].includes(value.toLowerCase()); return <article className="health-card" key={key}><span className={`health-icon ${good ? "good" : "bad"}`}><Icon name={key === "database" ? "folder" : key === "ai" ? "assistant" : key === "storage" ? "files" : "health"}/></span><div><small>{label[key] ? t(label[key]) : key}</small><strong>{value}</strong><p>{description[key] ? t(description[key]) : ""}</p></div><span className={`health-state ${good ? "good" : "bad"}`}>{good ? t("health.ready") : t("health.error")}</span></article>; })}</div>}</LoadState>
  </section>;
}
