import { useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { SUBSCRIPTION_PLANS, isSubscriptionActive } from "@nivasafe/domain";
import { api, clearSession, download, getCurrentRole, getSession, isSessionRemembered, saveSession, useLoad } from "../../api/client";
import { EmptyState, Icon, PageHeader, SectionCard, StatusBadge, formatDate, type IconName, useDialog } from "../../components/UI";
import { AutoSaveForm, clearAutoSaveDraft } from "../../forms/AutoSaveForm";
import { scopedDraftKey } from "../../forms/autoSave";

export function LoadState<T>({ state, children, empty = "داده‌ای ثبت نشده است." }: { state: ReturnType<typeof useLoad<T>>; children: (data: T) => ReactNode; empty?: string }) {
  if (state.loading) return <div className="state"><div className="spinner"/><p>در حال دریافت اطلاعات…</p></div>;
  if (state.error) return <div className="state error-state"><span className="state-icon"><Icon name="warning" size={27}/></span><h3>دریافت اطلاعات ناموفق بود</h3><p>{state.error}</p><button className="primary" onClick={state.reload}>تلاش دوباره</button></div>;
  if (!state.data || (Array.isArray(state.data) && !state.data.length)) return <EmptyState title={empty} icon="folder"/>;
  return <>{children(state.data)}</>;
}

type DashboardData = {
  counters: Record<string, number>;
  riskDistribution: Array<{ riskLevel: string; _count: number }>;
  actionDistribution: Array<{ status: string; _count: number }>;
  recent: { fmeas: Array<{ id: string; title: string; code: string; status: string; updatedAt?: string }>; rulas: Array<{ id: string; title: string; score: number; actionLevel: number; updatedAt?: string }> };
};

const kpis: Record<string, { label: string; caption: string; icon: IconName; tone: string; href: string }> = {
  projects: { label: "پروژه‌های فعال", caption: "پروژه‌های ثبت‌شده", icon: "projects", tone: "teal", href: "/projects" },
  fmeas: { label: "ارزیابی FMEA", caption: "ارزیابی‌های ریسک", icon: "fmea", tone: "blue", href: "/fmea" },
  rulas: { label: "ارزیابی RULA", caption: "ارزیابی‌های ارگونومی", icon: "rula", tone: "violet", href: "/rula" },
  openActions: { label: "اقدامات باز", caption: "نیازمند پیگیری", icon: "actions", tone: "amber", href: "/actions" },
  overdueActions: { label: "اقدامات معوق", caption: "عبور از موعد", icon: "clock", tone: "orange", href: "/actions" },
  criticalItems: { label: "ریسک بحرانی", caption: "نیازمند اقدام فوری", icon: "warning", tone: "red", href: "/fmea" },
  members: { label: "اعضای سازمان", caption: "کاربران فعال", icon: "members", tone: "teal", href: "/members" },
  knowledgeDocs: { label: "اسناد پایگاه دانش", caption: "منابع قابل استفاده", icon: "knowledge", tone: "violet", href: "/knowledge" },
  pendingAI: { label: "تحلیل‌های در انتظار", caption: "صف دستیار هوشمند", icon: "assistant", tone: "blue", href: "/assistant" },
};
const riskLabels: Record<string, string> = { LOW: "کم", MEDIUM: "متوسط", HIGH: "زیاد", CRITICAL: "بحرانی" };
const riskColors: Record<string, string> = { LOW: "#2b9a6f", MEDIUM: "#e0a129", HIGH: "#e4772c", CRITICAL: "#d94f4f" };
const dashboardWidgetLabels: Record<string, string> = { "section:risk": "توزیع سطح ریسک", "section:actions": "اقدامات اصلاحی", "section:recent": "آخرین ارزیابی‌ها", "section:quick": "دسترسی سریع", "kpi:projects": "پروژه‌های فعال", "kpi:fmeas": "FMEA", "kpi:rulas": "ارزیابی‌های ارگونومی", "kpi:openActions": "اقدامات باز", "kpi:overdueActions": "اقدامات معوق", "kpi:criticalItems": "ریسک بحرانی", "kpi:members": "اعضای سازمان", "kpi:knowledgeDocs": "اسناد پایگاه دانش", "kpi:pendingAI": "تحلیل‌های در انتظار" };
const defaultDashboardWidgetOrder = Object.keys(dashboardWidgetLabels);

function loadDashboardList(key: string, fallback: string[]) {
  try {
    const value = JSON.parse(localStorage.getItem(key) ?? "null") as unknown;
    return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : fallback;
  } catch { return fallback; }
}

function normalizeDashboardOrder(value: string[]) {
  const known = value.filter((item, index) => (dashboardWidgetLabels[item] || item.startsWith("kpi:")) && value.indexOf(item) === index);
  return [...known, ...defaultDashboardWidgetOrder.filter((item) => !known.includes(item))];
}

export function DashboardPage() {
  const state = useLoad<DashboardData>("/dashboard");
  const [customizing, setCustomizing] = useState(false);
  const { session, orgId } = getSession();
  const widgetStorageKey = `nivasafe-dashboard-widgets:${session?.user.id ?? "guest"}:${orgId || "default"}`;
  const orderStorageKey = `${widgetStorageKey}:order`;
  const [hiddenWidgets, setHiddenWidgets] = useState<string[]>(() => loadDashboardList(widgetStorageKey, []));
  const [widgetOrder, setWidgetOrder] = useState<string[]>(() => normalizeDashboardOrder(loadDashboardList(orderStorageKey, defaultDashboardWidgetOrder)));
  const visibleWidget = (id: string) => !hiddenWidgets.includes(id);
  function toggleWidget(id: string) { setHiddenWidgets((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; localStorage.setItem(widgetStorageKey, JSON.stringify(next)); return next; }); }
  function moveWidgetTo(source: string, target: string) { setWidgetOrder((current) => { const next = [...current]; if (!next.includes(source)) next.push(source); if (!next.includes(target)) next.push(target); const from = next.indexOf(source); const to = next.indexOf(target); if (from < 0 || to < 0 || from === to) return current; next.splice(from, 1); next.splice(to, 0, source); localStorage.setItem(orderStorageKey, JSON.stringify(next)); return next; }); }
  function moveWidget(id: string, delta: -1 | 1, order = widgetOrder) { const index = order.indexOf(id); const target = order[index + delta]; if (target) moveWidgetTo(id, target); }
  function resetWidgets() { setHiddenWidgets([]); setWidgetOrder(defaultDashboardWidgetOrder); localStorage.removeItem(widgetStorageKey); localStorage.removeItem(orderStorageKey); }
  return <section className="page-shell">
    <PageHeader eyebrow="مرکز کنترل HSE" title="داشبورد مدیریتی" description="تصویر لحظه‌ای از ریسک‌ها، ارزیابی‌ها و اقدامات اصلاحی سازمان" actions={<><button className="ghost" type="button" onClick={() => setCustomizing((value) => !value)}><Icon name="dashboard"/> {customizing ? "بستن تنظیمات" : "شخصی‌سازی داشبورد"}</button><Link className="primary button-link" to="/choose-path"><Icon name="plus"/> ایجاد ارزیابی جدید</Link></>}/>
    <LoadState state={state}>{(data) => {
      const totalRisk = data.riskDistribution.reduce((sum, item) => sum + Number(item._count), 0) || 1;
      const recent = [
        ...data.recent.fmeas.map((item) => ({ type: "FMEA", title: item.title, meta: item.code, value: item.status, date: item.updatedAt, href: "/fmea" })),
        ...data.recent.rulas.map((item) => ({ type: "RULA", title: item.title, meta: `سطح اقدام ${item.actionLevel}`, value: `امتیاز ${item.score}`, date: item.updatedAt, href: "/rula" })),
      ].slice(0, 6);
      const liveOrder = [...widgetOrder, ...Object.keys(data.counters).map((key) => `kpi:${key}`).filter((id) => !widgetOrder.includes(id))];
      function renderWidget(id: string): ReactNode {
        if (id.startsWith("kpi:")) {
          const key = id.slice(4); const value = data.counters[key]; if (value === undefined) return null;
          const item = kpis[key] ?? { label: key, caption: "", icon: "chart" as IconName, tone: "teal", href: "/" };
          return <Link to={item.href} className={`kpi-card dashboard-widget dashboard-kpi-widget ${item.tone}`} key={id} data-widget-id={id}><span className="kpi-icon"><Icon name={item.icon}/></span><div className="kpi-copy"><small>{item.label}</small><strong>{value.toLocaleString("fa-IR")}</strong><span>{item.caption}</span></div><Icon name="arrow" size={18} className="kpi-arrow"/></Link>;
        }
        if (id === "section:risk") return <SectionCard key={id} title="توزیع سطح ریسک" description="ترکیب ریسک‌های ثبت‌شده در FMEA" icon="chart" className="dashboard-widget dashboard-section-widget risk-panel">{!data.riskDistribution.length ? <EmptyState title="هنوز ریسکی ثبت نشده است" description="پس از ثبت ردیف‌های FMEA نمودار در این بخش نمایش داده می‌شود." icon="chart"/> : <div className="risk-bars">{data.riskDistribution.map((item) => <div className="risk-row" key={item.riskLevel}><div className="risk-row-head"><span><i style={{ background: riskColors[item.riskLevel] }}/>{riskLabels[item.riskLevel] ?? item.riskLevel}</span><strong>{item._count.toLocaleString("fa-IR")}</strong></div><div className="progress-track"><span style={{ width: `${Math.max(6, (item._count / totalRisk) * 100)}%`, background: riskColors[item.riskLevel] }}/></div></div>)}</div>}</SectionCard>;
        if (id === "section:actions") return <SectionCard key={id} title="وضعیت اقدامات اصلاحی" description="نمایش جریان اقدامات تا مرحله تکمیل" icon="actions" className="dashboard-widget dashboard-section-widget actions-panel">{!data.actionDistribution.length ? <EmptyState title="اقدامی ثبت نشده است" icon="actions"/> : <div className="action-summary">{data.actionDistribution.map((item) => <div className="summary-row" key={item.status}><StatusBadge value={item.status}/><strong>{item._count.toLocaleString("fa-IR")}</strong></div>)}</div>}<Link className="text-link" to="/actions">مشاهده همه اقدامات <Icon name="arrow" size={16}/></Link></SectionCard>;
        if (id === "section:recent") return <SectionCard key={id} title="آخرین ارزیابی‌ها" description="آخرین تغییرات در ارزیابی‌های سازمان" icon="activity" className="dashboard-widget dashboard-section-widget recent-panel">{!recent.length ? <EmptyState title="ارزیابی تازه‌ای وجود ندارد" icon="activity"/> : <div className="recent-list">{recent.map((item, index) => <Link to={item.href} className="recent-item" key={`${item.type}-${index}`}><span className={`recent-type ${item.type.toLowerCase()}`}>{item.type}</span><div><strong>{item.title}</strong><small>{item.meta}{item.date ? ` · ${formatDate(item.date)}` : ""}</small></div><span className="recent-value">{item.type === "FMEA" ? <StatusBadge value={item.value}/> : item.value}</span></Link>)}</div>}</SectionCard>;
        if (id === "section:quick") return <SectionCard key={id} title="دسترسی سریع" description="عملیات پرکاربرد سامانه" icon="sparkles" className="dashboard-widget dashboard-section-widget quick-panel"><div className="quick-actions"><Link to="/fmea"><Icon name="fmea"/><span><strong>FMEA جدید</strong><small>ارزیابی ریسک فرایند</small></span></Link><Link to="/rula"><Icon name="rula"/><span><strong>RULA جدید</strong><small>ارزیابی ارگونومی</small></span></Link><Link to="/actions"><Icon name="actions"/><span><strong>اقدام اصلاحی</strong><small>ثبت و پیگیری اقدام</small></span></Link><Link to="/assistant"><Icon name="assistant"/><span><strong>دستیار هوشمند</strong><small>راهنمای تخصصی HSE</small></span></Link></div></SectionCard>;
        return null;
      }
      return <>
        {customizing && <div className="dashboard-customizer"><div><strong>چیدمان داشبورد</strong><small>هر ویجت را روشن/خاموش کنید یا با دکمه‌های جابه‌جایی و کشیدن، ترتیب نمایش را تغییر دهید؛ تنظیمات برای همین سازمان و کاربر ذخیره می‌شود.</small></div><div className="widget-checks">{liveOrder.map((id, index) => <div className="widget-control" key={id} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", id)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const source = event.dataTransfer.getData("text/plain"); if (source) moveWidgetTo(source, id); }}><label><input type="checkbox" checked={visibleWidget(id)} onChange={() => toggleWidget(id)}/><span>{dashboardWidgetLabels[id] ?? id}</span></label><div className="widget-order-actions"><button type="button" className="icon-button" aria-label={`جابجایی ${dashboardWidgetLabels[id] ?? id} به بالا`} title="بالا" disabled={index === 0} onClick={() => moveWidget(id, -1, liveOrder)}><Icon name="arrow" size={14} className="widget-arrow-up"/></button><button type="button" className="icon-button" aria-label={`جابجایی ${dashboardWidgetLabels[id] ?? id} به پایین`} title="پایین" disabled={index === liveOrder.length - 1} onClick={() => moveWidget(id, 1, liveOrder)}><Icon name="arrow" size={14} className="widget-arrow-down"/></button></div></div>)}</div><button type="button" className="text-button" onClick={resetWidgets}>بازگردانی همه ویجت‌ها</button></div>}
        <div className="dashboard-widgets">{liveOrder.filter(visibleWidget).map(renderWidget)}</div>
      </>;
    }}</LoadState>
  </section>;
}

type OrganizationDetails = { id: string; nameFa: string; nameEn: string; active?: boolean; nationalId?: string | null; industry?: string | null; employeeCount?: number | null; timezone?: string; defaultLocale?: string; riskMedium?: number; riskHigh?: number; riskCritical?: number; subscriptionPlan?: string; subscriptionStatus?: string; subscriptionProvider?: string; subscriptionStartedAt?: string; subscriptionExpiresAt?: string | null };
export function OrganizationsPage() {
  const current = useLoad<OrganizationDetails>("/organizations/current"); const organizations = useLoad<OrganizationDetails[]>("/organizations"); const dashboard = useLoad<DashboardData>("/dashboard");
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const dialog = useDialog(); const role = getCurrentRole(); const canManage = ["SUPER_ADMIN", "ORG_ADMIN"].includes(role); const isSuperAdmin = role === "SUPER_ADMIN";
  const { session, orgId } = getSession();
  const editDraftKey = scopedDraftKey("organization-edit", session?.user.id, orgId);
  const createDraftKey = scopedDraftKey("organization-create", session?.user.id, orgId);
  const subscriptionDraftKey = scopedDraftKey("subscription-change", session?.user.id, orgId);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); try { await api("/organizations/current", { method: "PATCH", body: JSON.stringify({ nameFa: form.get("nameFa"), nameEn: form.get("nameEn"), nationalId: form.get("nationalId") || null, industry: form.get("industry") || null, employeeCount: form.get("employeeCount") ? Number(form.get("employeeCount")) : null }) }); await clearAutoSaveDraft(editDraftKey); current.reload(); organizations.reload(); setMessage("اطلاعات سازمان ذخیره شد."); } catch (reason) { setError((reason as Error).message); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); try { const result = await api<OrganizationDetails>("/organizations", { method: "POST", body: JSON.stringify({ nameFa: form.get("nameFa"), nameEn: form.get("nameEn"), industry: form.get("industry") || null, employeeCount: form.get("employeeCount") ? Number(form.get("employeeCount")) : null, subscriptionPlan: form.get("subscriptionPlan") || "STARTER", defaultLocale: "fa" }) }); await clearAutoSaveDraft(createDraftKey); const session = getSession().session; if (session) saveSession({ ...session, organizations: [...session.organizations, { id: result.data.id, nameFa: result.data.nameFa, nameEn: result.data.nameEn, role: "ORG_ADMIN", active: result.data.active, subscriptionPlan: result.data.subscriptionPlan, subscriptionStatus: result.data.subscriptionStatus, subscriptionExpiresAt: result.data.subscriptionExpiresAt }] }, isSessionRemembered()); localStorage.setItem("nivasafe-org", result.data.id); event.currentTarget.reset(); organizations.reload(); current.reload(); setMessage(result.data.subscriptionStatus === "PENDING_PAYMENT" ? "شرکت ایجاد شد؛ برای فعال‌شدن دسترسی، اشتراک همین شرکت را پرداخت کنید." : "شرکت جدید ایجاد شد و دوره آزمایشی آن فعال است."); } catch (reason) { setError((reason as Error).message); } }
  async function activateSubscription(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); try { const result = await api<OrganizationDetails>("/organizations/current/subscription/checkout", { method: "POST", body: JSON.stringify({ subscriptionPlan: form.get("subscriptionPlan") || "STARTER" }) }); await clearAutoSaveDraft(subscriptionDraftKey); const session = getSession().session; if (session) saveSession({ ...session, organizations: session.organizations.map((item) => item.id === result.data.id ? { ...item, subscriptionPlan: result.data.subscriptionPlan, subscriptionStatus: result.data.subscriptionStatus, subscriptionExpiresAt: result.data.subscriptionExpiresAt } : item) }, isSessionRemembered()); current.reload(); organizations.reload(); setMessage("اشتراک این شرکت با موفقیت فعال/تمدید شد."); } catch (reason) { setError((reason as Error).message); } }
  async function cancelSubscription() { if (!(await dialog.confirm("اشتراک شرکت فعال لغو شود؟ دسترسی پس از لغو متوقف می‌شود."))) return; setError(""); try { const result = await api<OrganizationDetails>("/organizations/current/subscription/cancel", { method: "POST" }); const session = getSession().session; if (session) saveSession({ ...session, organizations: session.organizations.map((item) => item.id === result.data.id ? { ...item, subscriptionStatus: result.data.subscriptionStatus, subscriptionExpiresAt: result.data.subscriptionExpiresAt } : item) }, isSessionRemembered()); current.reload(); organizations.reload(); setMessage("اشتراک شرکت لغو شد."); } catch (reason) { setError((reason as Error).message); } }
  async function setOrganizationActive(organization: OrganizationDetails) { const next = organization.active === false; if (!(await dialog.confirm(next ? `فعال‌سازی شرکت «${organization.nameFa}» تأیید شود؟` : `غیرفعال‌سازی شرکت «${organization.nameFa}» تأیید شود؟`))) return; if (!(await dialog.confirm(next ? "با تأیید دوم، دسترسی شرکت و کاربران آن برقرار می‌شود. ادامه می‌دهید؟" : "با تأیید دوم، دسترسی همه کاربران این شرکت متوقف می‌شود. ادامه می‌دهید؟"))) return; try { await api(`/organizations/${organization.id}/status`, { method: "PATCH", body: JSON.stringify({ active: next, confirmation: next ? "ACTIVATE" : "DEACTIVATE" }) }); const session = getSession().session; if (session) saveSession({ ...session, organizations: session.organizations.map((item) => item.id === organization.id ? { ...item, active: next } : item) }, isSessionRemembered()); organizations.reload(); current.reload(); setMessage(next ? "شرکت فعال شد." : "شرکت موقتاً غیرفعال شد."); } catch (reason) { setError((reason as Error).message); } }
  async function deactivate() { if (!(await dialog.confirm("برای غیرفعال‌کردن سازمان تأیید کنید."))) return; if (!(await dialog.confirm("این عملیات دسترسی همه اعضا را متوقف می‌کند. ادامه می‌دهید؟"))) return; try { await api("/organizations/current/deactivate", { method: "POST" }); clearSession(); window.location.assign("/login"); } catch (reason) { setError((reason as Error).message); } }
  return <section className="page-shell"><PageHeader eyebrow="مدیریت سازمان" title="سازمان‌ها و پنل مدیریتی" description="مدیریت اطلاعات سازمان، اشتراک‌ها، اعضا و شاخص‌های کلیدی ریسک"/>{error && <div className="alert error"><Icon name="warning"/>{error}</div>}{message && <div className="alert success"><Icon name="check"/>{message}</div>}
    <LoadState state={dashboard}>{(data) => <div className="kpi-grid crm-kpis">{Object.entries(data.counters).map(([key, value]) => { const item = kpis[key] ?? { label: key === "members" ? "اعضای فعال" : key === "knowledgeDocs" ? "اسناد دانش" : key === "pendingAI" ? "تحلیل‌های در صف" : key, caption: "شاخص سازمان", icon: (key === "members" ? "members" : key === "knowledgeDocs" ? "knowledge" : "assistant") as IconName, tone: "teal", href: "/" }; return <div className={`kpi-card ${item.tone}`} key={key}><span className="kpi-icon"><Icon name={item.icon}/></span><div className="kpi-copy"><small>{item.label}</small><strong>{value.toLocaleString("fa-IR")}</strong><span>{item.caption}</span></div></div>; })}</div>}</LoadState>
    <LoadState state={current} empty="اطلاعات شرکت فعال در دسترس نیست.">{(organization) => <SectionCard title="اشتراک شرکت فعال" description="هر شرکت اشتراک مستقل، وضعیت و تاریخ پایان جداگانه دارد." icon="shield"><div className="subscription-panel"><div className="subscription-summary"><div><strong>{SUBSCRIPTION_PLANS.find((plan) => plan.id === organization.subscriptionPlan)?.titleFa ?? organization.subscriptionPlan ?? "شروع"}</strong><small>ارائه‌دهنده: {organization.subscriptionProvider === "local" ? "آزمایشی محلی" : organization.subscriptionProvider === "legacy" ? "سازمان موجود" : organization.subscriptionProvider ?? "ثبت‌نشده"}</small></div><StatusBadge value={organization.subscriptionStatus ?? "ACTIVE"}/><span className="subscription-expiry">{organization.subscriptionExpiresAt ? `تا ${new Date(organization.subscriptionExpiresAt).toLocaleDateString("fa-IR")}` : "بدون تاریخ انقضا"}</span></div>{canManage && <AutoSaveForm storageKey={subscriptionDraftKey} className="inline-form subscription-form" onSubmit={activateSubscription}><label>طرح اشتراک<select name="subscriptionPlan" defaultValue={organization.subscriptionPlan ?? "STARTER"}>{SUBSCRIPTION_PLANS.map((plan) => <option key={plan.id} value={plan.id}>{plan.titleFa} — {plan.descriptionFa}</option>)}</select></label><button className="primary"><Icon name="check"/> فعال‌سازی / تمدید</button>{isSubscriptionActive(organization.subscriptionStatus ?? "ACTIVE", organization.subscriptionExpiresAt) && <button className="ghost danger-button" type="button" onClick={() => void cancelSubscription()}>لغو اشتراک</button>}</AutoSaveForm>}<small className="field-hint">در محیط توسعه، این دکمه پرداخت آزمایشی محلی را شبیه‌سازی می‌کند؛ در production به درگاه پرداخت متصل می‌شود.</small></div></SectionCard>}</LoadState>
    {canManage && <div className="form-panels"><SectionCard title="اطلاعات سازمان فعال" description="تمام اطلاعات پس از ثبت قابل ویرایش هستند." icon="projects"><LoadState state={current} empty="اطلاعات سازمان در دسترس نیست.">{(organization) => <AutoSaveForm storageKey={editDraftKey} className="form-grid" onSubmit={save}><label>نام فارسی<input name="nameFa" defaultValue={organization.nameFa} required/></label><label>نام انگلیسی<input name="nameEn" defaultValue={organization.nameEn} required dir="ltr"/></label><label>شناسه ملی<input name="nationalId" defaultValue={organization.nationalId ?? ""}/></label><label>نوع صنعت<input name="industry" defaultValue={organization.industry ?? ""}/></label><label>تعداد کارکنان<input name="employeeCount" type="number" min="0" defaultValue={organization.employeeCount ?? ""}/></label><button className="primary full"><Icon name="check"/> ذخیره اطلاعات</button></AutoSaveForm>}</LoadState></SectionCard><SectionCard title="ایجاد سازمان جدید" description="برای مدیریت چند شرکت از یک حساب استفاده کنید؛ برای هر شرکت طرح اشتراک جداگانه انتخاب می‌شود." icon="plus"><AutoSaveForm storageKey={createDraftKey} className="form-grid" onSubmit={create}><label>نام فارسی<input name="nameFa" required/></label><label>نام انگلیسی<input name="nameEn" required dir="ltr"/></label><label>نوع صنعت<input name="industry"/></label><label>تعداد کارکنان<input name="employeeCount" type="number" min="0"/></label><label className="full">طرح اشتراک شرکت<select name="subscriptionPlan" defaultValue="STARTER">{SUBSCRIPTION_PLANS.map((plan) => <option key={plan.id} value={plan.id}>{plan.titleFa} — {plan.descriptionFa}</option>)}</select></label><button className="primary full"><Icon name="plus"/> ایجاد شرکت و اشتراک جداگانه</button></AutoSaveForm></SectionCard></div>}
    <SectionCard title="شرکت‌های قابل دسترس" description={`${(organizations.data?.length ?? 0).toLocaleString("fa-IR")} فضای کاری مستقل`} icon="members"><LoadState state={organizations} empty="شرکت دیگری ثبت نشده است.">{(data) => <div className="simple-list">{data.map((organization) => <div className="simple-list-row" key={organization.id}><div><strong>{organization.nameFa}</strong><small>{organization.industry || "صنعت ثبت نشده"} · {organization.employeeCount ? `${organization.employeeCount.toLocaleString("fa-IR")} نفر` : "تعداد کارکنان ثبت نشده"}</small></div><div className="organization-row-actions"><StatusBadge value={organization.subscriptionStatus ?? "ACTIVE"}/><span className={`organization-status ${organization.active === false ? "inactive" : "active"}`}>{organization.active === false ? "غیرفعال" : "فعال"}</span><button className="text-button" type="button" onClick={() => { localStorage.setItem("nivasafe-org", organization.id); window.location.assign("/"); }}>{organization.id === current.data?.id ? "ورود به شرکت" : "ورود"}</button>{isSuperAdmin && <button className="text-button" type="button" onClick={() => void setOrganizationActive(organization)}>{organization.active === false ? "فعال‌کردن" : "غیرفعال‌کردن"}</button>}</div></div>)}</div>}</LoadState></SectionCard>
    {canManage && !isSuperAdmin && <button className="ghost danger-button" onClick={() => void deactivate()}>غیرفعال‌کردن سازمان فعال</button>}
  </section>;
}

type Project = { id: string; name: string; code: string; status: string; description?: string; updatedAt?: string };
type Process = { id: string; projectId: string; name: string };
type Activity = { id: string; projectId: string; processId?: string; title: string; location?: string };

export function ProjectsPage() {
  const projects = useLoad<Project[]>("/projects");
  const processes = useLoad<Process[]>("/processes");
  const activities = useLoad<Activity[]>("/activities");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const dialog = useDialog();
  const canManage = ["SUPER_ADMIN", "ORG_ADMIN", "HSE_MANAGER"].includes(getCurrentRole());
  const { session, orgId } = getSession();
  const projectDraftKey = scopedDraftKey("project-create", session?.user.id, orgId);
  const processDraftKey = scopedDraftKey("process-create", session?.user.id, orgId);
  const activityDraftKey = scopedDraftKey("activity-create", session?.user.id, orgId);
  async function create(path: string, event: FormEvent<HTMLFormElement>, reload: () => void, message: string, draftKey: string) {
    event.preventDefault(); setError(""); setSuccess("");
    const form = event.currentTarget;
    const payload = Object.fromEntries(new FormData(form));
    for (const [key, value] of Object.entries(payload)) if (value === "") delete payload[key];
    try { await api(path, { method: "POST", body: JSON.stringify(payload) }); await clearAutoSaveDraft(draftKey); form.reset(); reload(); setSuccess(message); }
    catch (reason) { setError((reason as Error).message); }
  }
  async function rename(path: string, id: string, current: string, reload: () => void) { const name = (await dialog.prompt("نام جدید را وارد کنید.", current))?.trim(); if (!name || name === current) return; try { await api(`${path}/${id}`, { method: "PATCH", body: JSON.stringify(path === "/activities" ? { title: name } : { name }) }); reload(); setSuccess("تغییرات ذخیره شد."); } catch (reason) { setError((reason as Error).message); } }
  async function remove(path: string, id: string, label: string, reload: () => void) { if (!(await dialog.confirm(`${label} حذف شود؟`))) return; try { await api(`${path}/${id}`, { method: "DELETE" }); reload(); setSuccess("مورد انتخاب‌شده حذف شد."); } catch (reason) { setError((reason as Error).message); } }
  const counts = { projects: projects.data?.length ?? 0, processes: processes.data?.length ?? 0, activities: activities.data?.length ?? 0 };
  return <section className="page-shell">
    <PageHeader eyebrow="ساختار عملیاتی" title="پروژه‌ها و فرایندها" description="پروژه‌ها، فرایندها و فعالیت‌های شغلی را در یک ساختار یکپارچه مدیریت کنید."/>
    {error && <div className="alert error"><Icon name="warning"/>{error}</div>}{success && <div className="alert success"><Icon name="check"/>{success}</div>}
    <div className="mini-stats"><div><Icon name="projects"/><strong>{counts.projects.toLocaleString("fa-IR")}</strong><span>پروژه</span></div><div><Icon name="activity"/><strong>{counts.processes.toLocaleString("fa-IR")}</strong><span>فرایند</span></div><div><Icon name="folder"/><strong>{counts.activities.toLocaleString("fa-IR")}</strong><span>فعالیت</span></div></div>
    {canManage && <div className="form-panels">
      <SectionCard title="پروژه جدید" description="تعریف دامنه اصلی فعالیت سازمان" icon="projects">
        <AutoSaveForm storageKey={projectDraftKey} className="form-grid" onSubmit={(event) => create("/projects", event, projects.reload, "پروژه با موفقیت ایجاد شد.", projectDraftKey)}>
          <label>نام پروژه<input name="name" placeholder="مثلاً توسعه خط تولید" required/></label><label>کد یکتا<input name="code" placeholder="مثلاً PRJ-001" required/></label><label className="full">شرح پروژه<textarea name="description" rows={3} placeholder="هدف و محدوده پروژه را بنویسید"/></label><button className="primary full"><Icon name="plus"/> ایجاد پروژه</button>
        </AutoSaveForm>
      </SectionCard>
      <SectionCard title="فرایند جدید" description="فرایند را به پروژه مربوط متصل کنید" icon="activity">
        <AutoSaveForm storageKey={processDraftKey} className="form-grid" onSubmit={(event) => create("/processes", event, processes.reload, "فرایند با موفقیت ایجاد شد.", processDraftKey)}>
          <label className="full">پروژه<select name="projectId" required><option value="">انتخاب پروژه</option>{projects.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="full">نام فرایند<input name="name" placeholder="مثلاً مونتاژ قطعات" required/></label><label className="full">شرح<textarea name="description" rows={3} placeholder="شرح کوتاه فرایند"/></label><button className="primary full"><Icon name="plus"/> ایجاد فرایند</button>
        </AutoSaveForm>
      </SectionCard>
    </div>}
    {canManage && <SectionCard title="ثبت فعالیت شغلی" description="فعالیت را به پروژه و در صورت نیاز به فرایند متصل کنید" icon="plus">
      <AutoSaveForm storageKey={activityDraftKey} className="inline-form" onSubmit={(event) => create("/activities", event, activities.reload, "فعالیت با موفقیت ثبت شد.", activityDraftKey)}>
        <label>پروژه<select name="projectId" required><option value="">انتخاب پروژه</option>{projects.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>فرایند<select name="processId"><option value="">بدون فرایند</option>{processes.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>عنوان فعالیت<input name="title" placeholder="عنوان فعالیت" required/></label><label>محل انجام<input name="location" placeholder="کارگاه، سالن، سایت…"/></label><button className="primary"><Icon name="plus"/> ثبت فعالیت</button>
      </AutoSaveForm>
    </SectionCard>}
    <SectionCard title="فهرست پروژه‌ها" description="خلاصه ساختار و وضعیت پروژه‌های سازمان" icon="folder">
      <LoadState state={projects} empty="هنوز پروژه‌ای ایجاد نشده است.">{(data) => <div className="project-cards">{data.map((project) => {
        const processCount = processes.data?.filter((x) => x.projectId === project.id).length ?? 0;
        const activityCount = activities.data?.filter((x) => x.projectId === project.id).length ?? 0;
        return <article className="project-card" key={project.id}><div className="project-top"><span className="project-code">{project.code}</span><StatusBadge value={project.status}/></div><h3>{project.name}</h3><p>{project.description || "برای این پروژه توضیحی ثبت نشده است."}</p><div className="project-meta"><span><Icon name="activity" size={16}/>{processCount.toLocaleString("fa-IR")} فرایند</span><span><Icon name="folder" size={16}/>{activityCount.toLocaleString("fa-IR")} فعالیت</span></div>{canManage && <div className="card-actions"><span onClick={() => void rename("/projects", project.id, project.name, projects.reload)}><Icon name="activity" size={15}/> ویرایش</span><span className="danger-link" onClick={() => void remove("/projects", project.id, `پروژه «${project.name}»`, projects.reload)}><Icon name="trash" size={15}/> حذف</span></div>}</article>;
      })}</div>}</LoadState>
    </SectionCard>
    {canManage && <div className="form-panels"><SectionCard title="فهرست فرایندها" description="ویرایش یا حذف فرایندهای سازمان" icon="activity"><LoadState state={processes} empty="فرایندی ثبت نشده است.">{(data) => <div className="simple-list">{data.map((item) => <div className="simple-list-row" key={item.id}><div><strong>{item.name}</strong><small>{projects.data?.find((project) => project.id === item.projectId)?.name ?? "پروژه نامشخص"}</small></div><div className="card-actions"><span onClick={() => void rename("/processes", item.id, item.name, processes.reload)}>ویرایش</span><span className="danger-link" onClick={() => void remove("/processes", item.id, `فرایند «${item.name}»`, processes.reload)}>حذف</span></div></div>)}</div>}</LoadState></SectionCard><SectionCard title="فهرست فعالیت‌ها" description="ویرایش یا حذف فعالیت‌های شغلی" icon="folder"><LoadState state={activities} empty="فعالیتی ثبت نشده است.">{(data) => <div className="simple-list">{data.map((item) => <div className="simple-list-row" key={item.id}><div><strong>{item.title}</strong><small>{item.location || "محل ثبت نشده"}</small></div><div className="card-actions"><span onClick={() => void rename("/activities", item.id, item.title, activities.reload)}>ویرایش</span><span className="danger-link" onClick={() => void remove("/activities", item.id, `فعالیت «${item.title}»`, activities.reload)}>حذف</span></div></div>)}</div>}</LoadState></SectionCard></div>}
  </section>;
}

type Action = { id: string; title: string; description?: string; priority: string; status: string; progress: number; dueDate?: string; assigneeName?: string };
export function ActionsPage() {
  const state = useLoad<Action[]>("/actions");
  const projects = useLoad<Project[]>("/projects");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const canEditActions = ["SUPER_ADMIN", "ORG_ADMIN", "HSE_MANAGER", "ASSESSOR"].includes(getCurrentRole());
  const { session, orgId } = getSession();
  const actionDraftKey = scopedDraftKey("action-create", session?.user.id, orgId);
  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setError("");
    try { await api("/actions", { method: "POST", body: JSON.stringify({ projectId: form.get("projectId"), title: form.get("title"), description: form.get("description"), priority: form.get("priority"), assigneeName: form.get("assigneeName") || null, dueDate: form.get("dueDate") || null }) }); await clearAutoSaveDraft(actionDraftKey); formElement.reset(); state.reload(); setMessage("اقدام اصلاحی ثبت شد."); }
    catch (reason) { setError((reason as Error).message); }
  }
  const openCount = state.data?.filter((x) => !["COMPLETED", "CANCELLED"].includes(x.status)).length ?? 0;
  const doneCount = state.data?.filter((x) => x.status === "COMPLETED").length ?? 0;
  return <section className="page-shell">
    <PageHeader eyebrow="چرخه بهبود" title="اقدامات اصلاحی" description="اقدامات را ثبت، مسئول مشخص و پیشرفت آن‌ها را تا تکمیل پیگیری کنید."/>
    {error && <div className="alert error"><Icon name="warning"/>{error}</div>}{message && <div className="alert success"><Icon name="check"/>{message}</div>}
    <div className="mini-stats"><div><Icon name="actions"/><strong>{openCount.toLocaleString("fa-IR")}</strong><span>اقدام باز</span></div><div><Icon name="check"/><strong>{doneCount.toLocaleString("fa-IR")}</strong><span>تکمیل‌شده</span></div><div><Icon name="chart"/><strong>{state.data?.length ? Math.round(state.data.reduce((s, x) => s + x.progress, 0) / state.data.length).toLocaleString("fa-IR") : "۰"}%</strong><span>میانگین پیشرفت</span></div></div>
    {canEditActions && <SectionCard title="ثبت اقدام جدید" description="برای هر اقدام، پروژه، اولویت، مسئول و موعد را مشخص کنید." icon="plus">
      <AutoSaveForm storageKey={actionDraftKey} className="action-form" onSubmit={create}><label>پروژه<select name="projectId" required><option value="">انتخاب پروژه</option>{projects.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>عنوان اقدام<input name="title" placeholder="مثلاً نصب حفاظ دستگاه" required/></label><label className="wide">شرح اقدام<input name="description" placeholder="شرح دقیق اقدام موردنیاز" required/></label><label>اولویت<select name="priority"><option value="MEDIUM">متوسط</option><option value="HIGH">زیاد</option><option value="CRITICAL">بحرانی</option><option value="LOW">کم</option></select></label><label>مسئول<input name="assigneeName" placeholder="نام مسئول"/></label><label>موعد انجام<input name="dueDate" type="date"/></label><button className="primary"><Icon name="plus"/> ثبت اقدام</button></AutoSaveForm>
    </SectionCard>}
    <SectionCard title="فهرست اقدامات" description="وضعیت هر اقدام را مستقیماً از جدول به‌روزرسانی کنید." icon="actions">
      <LoadState state={state} empty="اقدام اصلاحی ثبت نشده است.">{(data) => <div className="table-wrap"><table><thead><tr><th>اقدام</th><th>اولویت</th><th>وضعیت</th><th>پیشرفت</th><th>مسئول</th><th>موعد</th></tr></thead><tbody>{data.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.description}</small></td><td><StatusBadge value={item.priority}/></td><td>{canEditActions ? <select className="compact-select" value={item.status} onChange={async (event) => { try { setError(""); await api(`/actions/${item.id}`, { method: "PATCH", body: JSON.stringify({ status: event.target.value }) }); state.reload(); } catch (reason) { setError((reason as Error).message); } }}><option value="OPEN">باز</option><option value="IN_PROGRESS">در حال انجام</option><option value="WAITING_FOR_REVIEW">در انتظار بازبینی</option><option value="COMPLETED">تکمیل‌شده</option><option value="REJECTED">ردشده</option></select> : <StatusBadge value={item.status}/>}</td><td><div className="table-progress"><div><span style={{ width: `${item.progress}%` }}/></div><b>{item.progress.toLocaleString("fa-IR")}%</b></div></td><td>{item.assigneeName ?? "—"}</td><td>{formatDate(item.dueDate)}</td></tr>)}</tbody></table></div>}</LoadState>
    </SectionCard>
  </section>;
}

type KnowledgeAttachment = { id: string; originalName: string; mimeType: string; size: number; kind: string; createdAt: string; downloadPath: string };
type Knowledge = { id: string; title: string; content: string; tags: string[]; published?: boolean; aiReadable?: boolean; aiOnly?: boolean; isGlobal?: boolean; visibility?: string; visibleUserIds?: string[] | null; visibleOrganizationIds?: string[] | null; version?: number; updatedAt?: string; attachments?: KnowledgeAttachment[] };
type KnowledgeMember = { user: { id: string; displayName: string; email: string }; role: string; active: boolean };
type KnowledgeOrganization = { id: string; nameFa: string; nameEn: string; subscriptionPlan?: string; subscriptionStatus?: string };
type KnowledgeQuota = { plan: string; tokenLimit: number; usedTokens: number; remainingTokens: number; maxFileBytes: number; maxFileSizeLabel: string; canUpload: boolean };
const knowledgeFileSize = (size: number) => size > 1024 * 1024 ? `${(size / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.ceil(size / 1024))} KB`;
export function KnowledgePage() {
  const state = useLoad<Knowledge[]>("/knowledge");
  const quota = useLoad<KnowledgeQuota>("/knowledge/quota");
  const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const dialog = useDialog();
  const role = getCurrentRole(); const canManageKnowledge = ["SUPER_ADMIN", "ORG_ADMIN", "HSE_MANAGER"].includes(role); const canManageGlobal = role === "SUPER_ADMIN";
  const { session, orgId } = getSession();
  const knowledgeDraftKey = scopedDraftKey("knowledge-create", session?.user.id, orgId);
  const members = useLoad<KnowledgeMember[]>(canManageKnowledge ? "/members" : null);
  const organizations = useLoad<KnowledgeOrganization[]>(canManageGlobal ? "/organizations" : null);
  const filtered = useMemo(() => (state.data ?? []).filter((item) => `${item.title} ${item.content} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [state.data, query]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); let created: Knowledge | null = null; setError(""); setMessage(""); try { const visibility = String(form.get("visibility") || "ALL"); const aiOnly = form.get("aiOnly") === "on"; const isGlobal = canManageGlobal && form.get("isGlobal") === "on"; created = (await api<Knowledge>("/knowledge", { method: "POST", body: JSON.stringify({ title: form.get("title"), content: form.get("content"), tags: String(form.get("tags") || "").split(",").map((x) => x.trim()).filter(Boolean), published: !aiOnly && form.get("published") === "on", aiReadable: form.get("aiReadable") === "on", aiOnly, isGlobal, visibility, visibleUserIds: visibility === "SELECTED" ? form.getAll("visibleUserIds").map(String) : [], visibleOrganizationIds: isGlobal ? form.getAll("visibleOrganizationIds").map(String) : [] }) })).data; const file = form.get("file"); if (file instanceof File && file.size > 0) { const upload = new FormData(); upload.append("file", file); await api(`/knowledge/${created.id}/attachments`, { method: "POST", body: upload }); } await clearAutoSaveDraft(knowledgeDraftKey); element.reset(); state.reload(); quota.reload(); setMessage("سند دانش و فایل پیوست با موفقیت ثبت شد."); } catch (reason) { if (created) await api(`/knowledge/${created.id}`, { method: "DELETE" }).catch(() => undefined); setError((reason as Error).message); } }
  async function edit(item: Knowledge) { const title = (await dialog.prompt("عنوان جدید سند را وارد کنید.", item.title))?.trim(); if (!title || title === item.title) return; try { await api(`/knowledge/${item.id}`, { method: "PATCH", body: JSON.stringify({ title }) }); state.reload(); setMessage("سند ویرایش شد."); } catch (reason) { setError((reason as Error).message); } }
  async function togglePublished(item: Knowledge) { try { await api(`/knowledge/${item.id}`, { method: "PATCH", body: JSON.stringify({ published: item.published === false }) }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function toggleAiOnly(item: Knowledge) { try { await api(`/knowledge/${item.id}`, { method: "PATCH", body: JSON.stringify({ aiOnly: !item.aiOnly, published: item.aiOnly ? true : false }) }); state.reload(); setMessage(item.aiOnly ? "سند برای کاربران منتشر شد." : "سند فقط در اختیار هوش مصنوعی قرار گرفت."); } catch (reason) { setError((reason as Error).message); } }
  async function toggleAiReadable(item: Knowledge) { if (item.aiOnly && item.aiReadable !== false) return; try { await api(`/knowledge/${item.id}`, { method: "PATCH", body: JSON.stringify({ aiReadable: item.aiReadable === false }) }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function remove(item: Knowledge) { if (!(await dialog.confirm(`سند «${item.title}» حذف شود؟`))) return; try { await api(`/knowledge/${item.id}`, { method: "DELETE" }); state.reload(); quota.reload(); setMessage("سند حذف شد."); } catch (reason) { setError((reason as Error).message); } }
  async function removeAttachment(item: KnowledgeAttachment) { if (!(await dialog.confirm(`پیوست «${item.originalName}» حذف شود؟`))) return; try { await api(`/knowledge/attachments/${item.id}`, { method: "DELETE" }); state.reload(); quota.reload(); setMessage("پیوست حذف شد."); } catch (reason) { setError((reason as Error).message); } }
  async function downloadAttachment(item: KnowledgeAttachment) { try { const blob = await download(item.downloadPath); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = item.originalName; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { setError((reason as Error).message); } }
  return <section className="page-shell">
    <PageHeader eyebrow="دانش سازمانی" title="پایگاه دانش" description="دانش، فایل‌های تصویری و اسناد Word را با سطح نمایش و دسترسی هوش مصنوعی مدیریت کنید." actions={<div className="search-box"><Icon name="search"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="جستجو در اسناد…"/></div>}/>
    {error && <div className="alert error"><Icon name="warning"/>{error}</div>}{message && <div className="alert success"><Icon name="check"/>{message}</div>}
    {quota.data && <div className="knowledge-quota"><span><Icon name="assistant"/> مصرف توکن: <strong>{quota.data.usedTokens.toLocaleString("fa-IR")}</strong> از {quota.data.tokenLimit.toLocaleString("fa-IR")}</span><span>باقی‌مانده: <strong>{quota.data.remainingTokens.toLocaleString("fa-IR")}</strong> · حداکثر فایل {quota.data.maxFileSizeLabel}</span></div>}
    {canManageKnowledge && <SectionCard title="سند دانش جدید" description="انتشار برای کاربران، نمایش محدود و خوانش اختصاصی هوش مصنوعی را کنترل کنید." icon="plus">
      <AutoSaveForm storageKey={knowledgeDraftKey} className="knowledge-form" onSubmit={create}>
        <div className="knowledge-form-top"><label>عنوان سند<input name="title" placeholder="مثلاً راهنمای کنترل ریسک سقوط" required/></label><label>برچسب‌ها<input name="tags" placeholder="مثلاً HSE، ریسک، ارگونومی"/></label></div>
        <label className="knowledge-content-field">محتوای متنی سند<textarea name="content" rows={7} placeholder="متن راهنما، روش اجرایی یا دانش تخصصی را اینجا وارد کنید…"/></label>
        <div className="knowledge-options"><label>سطح نمایش<select name="visibility" defaultValue="ALL"><option value="ALL">همه کاربران شرکت</option><option value="SELECTED">کاربران منتخب</option><option value="HIDDEN">مخفی برای کاربران</option></select></label><label className="knowledge-user-select">کاربران منتخب<select name="visibleUserIds" multiple size={Math.min(4, Math.max(2, members.data?.length ?? 2))}>{members.data?.filter((member) => member.active).map((member) => <option key={member.user.id} value={member.user.id}>{member.user.displayName} · {member.user.email}</option>)}</select><small>برای انتخاب چند نفر، Ctrl یا لمس چندگانه را نگه دارید.</small></label>{canManageGlobal && <label className="knowledge-user-select">شرکت‌های مجاز برای دانش سراسری<select name="visibleOrganizationIds" multiple size={Math.min(4, Math.max(2, organizations.data?.length ?? 2))}>{organizations.data?.map((organization) => <option key={organization.id} value={organization.id}>{organization.nameFa}</option>)}</select><small>خالی بماند یعنی همه شرکت‌ها.</small></label>}<label className="checkbox-card"><input name="published" type="checkbox" defaultChecked/><span><strong>نمایش برای کاربران</strong><small>با خاموش‌کردن، سند در پنل کاربران پنهان می‌شود.</small></span></label><label className="checkbox-card"><input name="aiReadable" type="checkbox" defaultChecked/><span><strong>قابل خواندن برای AI</strong><small>در پاسخ‌های دستیار هوشمند استفاده شود.</small></span></label><label className="checkbox-card"><input name="aiOnly" type="checkbox"/><span><strong>فقط برای هوش مصنوعی</strong><small>هیچ کاربر انسانی، حتی مدیر سازمان، آن را نمی‌بیند.</small></span></label>{canManageGlobal && <label className="checkbox-card"><input name="isGlobal" type="checkbox"/><span><strong>دانش پیش‌فرض همه شرکت‌ها</strong><small>بدون انتخاب شرکت، برای همه شرکت‌ها فعال می‌شود.</small></span></label>}<label className="knowledge-file"><span>پیوست تصویر، Word، PDF یا Excel</span><input name="file" type="file" disabled={quota.data?.canUpload === false} accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx,.xlsx,.csv,.txt"/><small>حداکثر متناسب با طرح اشتراک: {quota.data?.maxFileSizeLabel ?? "۵ MB"}</small></label></div>
        <div className="knowledge-form-footer"><span className="knowledge-form-note"><Icon name="assistant" size={17}/> متن و فایل پس از ثبت به‌صورت کنترل‌شده در پایگاه دانش ذخیره می‌شوند.</span><button className="primary knowledge-submit"><Icon name="plus"/> ثبت سند</button></div>
      </AutoSaveForm>
    </SectionCard>}
    <SectionCard title="اسناد پایگاه دانش" description={`${filtered.length.toLocaleString("fa-IR")} سند قابل مشاهده`} icon="knowledge">
      {!filtered.length ? <EmptyState title="سندی مطابق جستجو پیدا نشد" description="عبارت دیگری را امتحان کنید یا سند تازه‌ای ثبت کنید." icon="search"/> : <div className="knowledge-grid">{filtered.map((item) => { const canEdit = canManageKnowledge && (!item.isGlobal || canManageGlobal); return <article className="knowledge-card" key={item.id}><div className="doc-icon"><Icon name="knowledge"/></div><div><div className="knowledge-title-row"><h3>{item.title}</h3><div className="knowledge-badges">{item.isGlobal && <span className="tag">{item.visibleOrganizationIds?.length ? "شرکت‌های منتخب" : "پیش‌فرض همه شرکت‌ها"}</span>}{item.aiOnly && <span className="tag">فقط AI</span>}{item.published === false && <StatusBadge value="DRAFT"/>}{item.aiReadable === false && <span className="tag">فقط انسانی</span>}</div></div><p>{item.content || "این سند به‌صورت فایل پیوست ثبت شده است."}</p><div className="tag-row">{item.tags.map((tag) => <span className="tag" key={tag}>#{tag}</span>)}{item.visibility && item.visibility !== "ALL" && <span className="tag">{item.visibility === "SELECTED" ? "منتخب" : "مخفی"}</span>}</div>{item.attachments?.length ? <div className="knowledge-attachments">{item.attachments.map((file) => <div className="knowledge-attachment" key={file.id}><Icon name="files" size={15}/><span title={file.originalName}>{file.originalName} · {knowledgeFileSize(file.size)}</span><button className="icon-button" title="دانلود" onClick={() => void downloadAttachment(file)}><Icon name="download" size={14}/></button>{canEdit && <button className="icon-button danger" title="حذف پیوست" onClick={() => void removeAttachment(file)}><Icon name="trash" size={14}/></button>}</div>)}</div> : null}{item.updatedAt && <small>به‌روزرسانی: {formatDate(item.updatedAt)} · نسخه {item.version ?? 1}</small>}{canEdit && <div className="knowledge-actions"><button className="text-button" onClick={() => void edit(item)}>ویرایش</button>{!item.aiOnly && <button className="text-button" onClick={() => void togglePublished(item)}>{item.published === false ? "انتشار" : "مخفی‌کردن"}</button>}{(!item.aiOnly || item.aiReadable === false) && <button className="text-button" onClick={() => void toggleAiReadable(item)}>{item.aiReadable === false ? "فعال‌سازی خوانش AI" : "قطع خوانش AI"}</button>}{canManageGlobal && <button className="text-button" onClick={() => void toggleAiOnly(item)}>{item.aiOnly ? "نمایش انسانی" : "فقط AI"}</button>}<button className="text-button danger-link" onClick={() => void remove(item)}>حذف</button></div>}</div></article>; })}</div>}
    </SectionCard>
  </section>;
}

type Notification = { id: string; title: string; message: string; readAt?: string; createdAt: string };
type NotificationPreferences = { emailEnabled: boolean; pushEnabled: boolean; riskAlerts: boolean; dueReminders: boolean };
export function NotificationsPage() {
  const state = useLoad<Notification[]>("/notifications"); const preferences = useLoad<NotificationPreferences>("/notifications/preferences"); const unread = state.data?.filter((x) => !x.readAt).length ?? 0; const [error, setError] = useState("");
  async function markOne(id: string) { try { setError(""); await api(`/notifications/${id}/read`, { method: "PATCH" }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function markAll() { try { setError(""); await api("/notifications/read-all", { method: "POST" }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function togglePreference(key: keyof NotificationPreferences, value: boolean) { try { setError(""); await api("/notifications/preferences", { method: "PATCH", body: JSON.stringify({ [key]: value }) }); preferences.reload(); } catch (reason) { setError((reason as Error).message); } }
  const preferenceData = preferences.data;
  return <section className="page-shell"><PageHeader eyebrow="مرکز پیام" title="اعلان‌ها" description={`${unread.toLocaleString("fa-IR")} اعلان خوانده‌نشده`} actions={<button className="ghost" disabled={!unread} onClick={() => void markAll()}><Icon name="check"/> خواندن همه</button>}/>
     {error && <div className="alert error"><Icon name="warning"/>{error}</div>}
     {preferenceData && <SectionCard title="تنظیمات اعلان" description="روش دریافت هشدارهای درون‌برنامه‌ای و بیرونی را انتخاب کنید." icon="notifications"><div className="preference-grid">{([ ["emailEnabled", "اعلان ایمیلی", "ارسال رویدادهای مهم به ایمیل"], ["pushEnabled", "اعلان مرورگر", "نمایش هشدار فوری روی دستگاه"], ["riskAlerts", "هشدار ریسک بحرانی", "اطلاع‌رسانی برای ریسک‌های سطح بحرانی"], ["dueReminders", "یادآوری موعد اقدام", "یادآوری اقدامات نزدیک به سررسید"] ] as const).map(([key, label, description]) => <label className="checkbox-card" key={key}><input type="checkbox" checked={preferenceData[key]} onChange={(event) => void togglePreference(key, event.target.checked)}/><span><strong>{label}</strong><small>{description}</small></span></label>)}</div></SectionCard>}
    <LoadState state={state} empty="اعلان جدیدی ندارید.">{(data) => <div className="notification-list">{data.map((item) => <article className={`notification-card ${item.readAt ? "read" : "unread"}`} key={item.id}><span className="notification-icon"><Icon name={item.title.includes("بحرانی") ? "warning" : "notifications"}/></span><div><div className="notification-title"><h3>{item.title}</h3>{!item.readAt && <span>جدید</span>}</div><p>{item.message}</p><small>{formatDate(item.createdAt, true)}</small></div>{!item.readAt && <button className="icon-button" title="علامت‌گذاری به‌عنوان خوانده‌شده" onClick={() => void markOne(item.id)}><Icon name="check"/></button>}</article>)}</div>}</LoadState>
  </section>;
}

type Audit = { id: string; action: string; entityType?: string; entityId?: string; createdAt: string; user?: { displayName: string; email?: string } };
export function AuditPage() {
  const state = useLoad<Audit[]>("/audit");
  return <section className="page-shell"><PageHeader eyebrow="ردیابی تغییرات" title="رویدادهای ممیزی" description="گزارش زمان‌مند عملیات کاربران و تغییرات مهم سامانه"/>
    <SectionCard title="گزارش رویدادها" icon="audit"><LoadState state={state} empty="رویدادی ثبت نشده است.">{(data) => <div className="table-wrap"><table><thead><tr><th>زمان</th><th>کاربر</th><th>رویداد</th><th>موجودیت</th></tr></thead><tbody>{data.map((item) => <tr key={item.id}><td>{formatDate(item.createdAt, true)}</td><td><strong>{item.user?.displayName ?? "سامانه"}</strong><small>{item.user?.email}</small></td><td><code className="event-code">{item.action}</code></td><td>{item.entityType ? `${item.entityType} · ${item.entityId ?? "—"}` : "—"}</td></tr>)}</tbody></table></div>}</LoadState></SectionCard>
  </section>;
}

export function HealthPage() {
  const state = useLoad<Record<string, string>>("/health");
  const label: Record<string, string> = { status: "وضعیت کلی", database: "پایگاه داده", redis: "صف و کش Redis", storage: "فضای ذخیره‌سازی", ai: "زیرساخت هوش مصنوعی" };
  const description: Record<string, string> = { status: "آمادگی سرویس Backend", database: "اتصال مستقیم به MySQL/MariaDB", redis: "در محیط محلی اختیاری است", storage: "محل نگهداری فایل‌های بارگذاری‌شده", ai: "آمادگی حالت Fallback و سرویس‌های خارجی" };
  return <section className="page-shell"><PageHeader eyebrow="پایش فنی" title="سلامت سامانه" description="وضعیت اتصال اجزای اصلی Backend و زیرساخت محلی" actions={<button className="ghost" onClick={state.reload}><Icon name="activity"/> بررسی مجدد</button>}/>
    <LoadState state={state}>{(data) => <div className="health-grid">{Object.entries(data).map(([key, value]) => { const good = !["down", "unhealthy", "failed"].includes(value.toLowerCase()); return <article className="health-card" key={key}><span className={`health-icon ${good ? "good" : "bad"}`}><Icon name={key === "database" ? "folder" : key === "ai" ? "assistant" : key === "storage" ? "files" : "health"}/></span><div><small>{label[key] ?? key}</small><strong>{value}</strong><p>{description[key]}</p></div><span className={`health-state ${good ? "good" : "bad"}`}>{good ? "آماده" : "خطا"}</span></article>; })}</div>}</LoadState>
  </section>;
}
