import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authenticate } from "../auth-guard.js";
import { audit, envelope, pageParams, parse, prisma, requireOrg, requirePermission } from "../core.js";

const documentSchema = z.object({ title: z.string().min(2), content: z.string().min(2), tags: z.array(z.string()).default([]), published: z.boolean().optional(), categoryId: z.string().uuid().nullable().optional() });
const categorySchema = z.object({ name: z.string().min(2), description: z.string().nullable().optional() });

export async function registerKnowledgeRoutes(app: FastifyInstance) {
  app.get("/api/v1/knowledge", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); const q = pageParams(request.query); const where = { organizationId, deletedAt: null, ...(q.search ? { OR: [{ title: { contains: q.search } }, { content: { contains: q.search } }] } : {}) }; const [data, total] = await Promise.all([prisma.knowledgeDocument.findMany({ where, include: { category: true }, skip: (q.page - 1) * q.limit, take: q.limit, orderBy: { updatedAt: "desc" } }), prisma.knowledgeDocument.count({ where })]); return envelope(data, { page: q.page, limit: q.limit, total }); });
  app.post("/api/v1/knowledge", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "knowledge.manage"); const item = await prisma.knowledgeDocument.create({ data: { organizationId, ...parse(documentSchema, request.body) } }); await audit(request, "KNOWLEDGE_CREATE", "KnowledgeDocument", item.id); return reply.code(201).send(envelope(item)); });
  app.patch("/api/v1/knowledge/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "knowledge.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const found = await prisma.knowledgeDocument.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!found) throw Object.assign(new Error("Document not found"), { statusCode: 404 }); const item = await prisma.knowledgeDocument.update({ where: { id }, data: parse(documentSchema.partial(), request.body) }); await audit(request, "KNOWLEDGE_UPDATE", "KnowledgeDocument", id); return envelope(item); });
  app.delete("/api/v1/knowledge/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "knowledge.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const result = await prisma.knowledgeDocument.updateMany({ where: { id, organizationId, deletedAt: null }, data: { deletedAt: new Date(), published: false } }); if (!result.count) throw Object.assign(new Error("Document not found"), { statusCode: 404 }); await audit(request, "KNOWLEDGE_DELETE", "KnowledgeDocument", id); return envelope({ success: true }); });
  app.get("/api/v1/knowledge/categories", { preHandler: authenticate }, async (request) => envelope(await prisma.knowledgeCategory.findMany({ where: { organizationId: requireOrg(request) }, orderBy: { name: "asc" } })));
  app.post("/api/v1/knowledge/categories", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "knowledge.manage"); return reply.code(201).send(envelope(await prisma.knowledgeCategory.create({ data: { organizationId, ...parse(categorySchema, request.body) } }))); });
  app.patch("/api/v1/knowledge/categories/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "knowledge.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const found = await prisma.knowledgeCategory.findFirst({ where: { id, organizationId } }); if (!found) throw Object.assign(new Error("Category not found"), { statusCode: 404 }); return envelope(await prisma.knowledgeCategory.update({ where: { id }, data: parse(categorySchema.partial(), request.body) })); });
  app.delete("/api/v1/knowledge/categories/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "knowledge.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const count = await prisma.knowledgeDocument.count({ where: { organizationId, categoryId: id, deletedAt: null } }); if (count) throw Object.assign(new Error("Category is in use"), { statusCode: 409, code: "CATEGORY_IN_USE" }); const result = await prisma.knowledgeCategory.deleteMany({ where: { id, organizationId } }); if (!result.count) throw Object.assign(new Error("Category not found"), { statusCode: 404 }); return envelope({ success: true }); });
}
