import { calculateRpn } from "@nivasafe/domain";
import { del as deleteDraft, get as getDraft, set as setDraft } from "idb-keyval";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { api, download, getSession, useLoad } from "../../api/client";
import { EmptyState, Icon, PageHeader, SectionCard, StatusBadge, formatDate, useDialog } from "../../components/UI";
import { AutoSaveForm, clearAutoSaveDraft } from "../../forms/AutoSaveForm";
import { scopedDraftKey } from "../../forms/autoSave";
import { useI18n } from "../../i18n";
import { LoadState } from "../general/GeneralPages";

type Project = { id: string; name: string; nameFa?: string; nameEn?: string };
type FmeaItem = { id: string; rowNumber: number; processStep: string; failureMode: string; effect: string; cause: string; severity: number; occurrence: number; detection: number; rpn: number; riskLevel: string; recommendation?: string };
type Fmea = { id: string; title: string; code: string; scope?: string; status: string; version: number; project: Project; items: FmeaItem[] };
type Rula = { id: string; title: string; subjectCode?: string; score: number; actionLevel: number; explanation: string; status: string; version: number; project: Project };
type VersionRow = { id: string; version: number; createdAt: string };
type DraftRecord = Record<string, unknown>;

function draftKeyFor(kind: "fmea" | "rula") {
  const { session, orgId } = getSession();
  return `nivasafe-draft:v1:${kind}:${session?.user.id ?? "guest"}:${orgId || "none"}`;
}

const canEdit = () => { const { session, orgId } = getSession(); return ["SUPER_ADMIN", "ORG_ADMIN", "HSE_MANAGER", "ASSESSOR"].includes(session?.organizations.find((org) => org.id === orgId)?.role ?? "VIEWER") || session?.user.globalRole === "SUPER_ADMIN"; };
async function saveBlob(path: string, filename: string) { const blob = await download(path); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

function snapshotForm(form: HTMLFormElement): DraftRecord {
  const snapshot = Object.fromEntries(new FormData(form).entries()) as DraftRecord;
  form.querySelectorAll<HTMLInputElement>('input[type="checkbox"][name]').forEach((input) => { snapshot[input.name] = input.checked; });
  return snapshot;
}

function queueDraft(form: HTMLFormElement, key: string, timer: React.MutableRefObject<number | null>, onSaved: (time: Date) => void, onError?: () => void) {
  if (timer.current !== null) window.clearTimeout(timer.current);
  timer.current = null;
  void setDraft(key, snapshotForm(form)).then(() => onSaved(new Date())).catch((reason) => { if (onError) onError(); else console.error("NIVASafe assessment draft persistence failed", reason); });
}

function draftValue(draft: DraftRecord | null, key: string, fallback = "") {
  const value = draft?.[key];
  return value === undefined || value === null ? fallback : String(value);
}

function projectName(project: Project, locale: "fa" | "en") {
  return locale === "en" ? project.nameEn ?? project.name : project.nameFa ?? project.name;
}

function AutoSaveStatus({ lastSaved }: { lastSaved: Date | null }) {
  const { locale, t } = useI18n();
  const timeLocale = locale === "en" ? "en-US" : "fa-IR";
  return <small className="autosave-status"><Icon name="check" size={14}/>{t("assessment.autosaveActive")}{lastSaved ? ` · ${t("assessment.lastSaved", { time: lastSaved.toLocaleTimeString(timeLocale, { hour: "2-digit", minute: "2-digit" }) })}` : ""}</small>;
}

function fmeaPayloadFromForm(form: HTMLFormElement) {
  const values = new FormData(form);
  return { projectId: values.get("projectId"), title: values.get("title"), code: values.get("code"), scope: values.get("scope") || null };
}

function fmeaPayloadFromDraft(value: unknown) {
  const draft = (value && typeof value === "object" ? value : {}) as DraftRecord;
  return { projectId: draft.projectId ?? "", title: draft.title ?? "", code: draft.code ?? "", scope: draft.scope || null };
}

export function FmeaPage() {
  const { locale, t } = useI18n();
  const numberLocale = locale === "en" ? "en-US" : "fa-IR";
  const draftKey = draftKeyFor("fmea");
  const state = useLoad<Fmea[]>("/fmea");
  const projects = useLoad<Project[]>("/projects");
  const [selected, setSelected] = useState("");
  const [draftNotice, setDraftNotice] = useState("");
  const [draftSyncAvailable, setDraftSyncAvailable] = useState(false);
  const [error, setError] = useState("");
  const [history, setHistory] = useState<VersionRow[]>([]);
  const [historyAssessment, setHistoryAssessment] = useState("");
  const [scores, setScores] = useState({ severity: 1, occurrence: 1, detection: 1 });
  const [wizardStep, setWizardStep] = useState(1);
  const [draft, setDraftState] = useState<DraftRecord | null>(null);
  const [lastSaved, setLastSaved] = useState<Date | null>(null);
  const dialog = useDialog();
  const formRef = useRef<HTMLFormElement>(null);
  const saveTimer = useRef<number | null>(null);
  const { session, orgId } = getSession();
  const itemDraftKey = scopedDraftKey(`fmea-item:${selected || "new"}`, session?.user.id, orgId);
  const selectedAssessment = state.data?.find((item) => item.id === selected);
  const previewRpn = calculateRpn(scores.severity, scores.occurrence, scores.detection);

  useEffect(() => { void getDraft(draftKey).then((value) => { if (value && typeof value === "object") { setDraftState(value as DraftRecord); setDraftNotice(t("assessment.draftAvailable", { type: "FMEA" })); setDraftSyncAvailable(true); } }); return () => { if (saveTimer.current !== null) window.clearTimeout(saveTimer.current); }; }, [draftKey, t]);
  function validateWizardStep() {
    const values = formRef.current ? new FormData(formRef.current) : null;
    const required = wizardStep === 1 ? [["projectId", t("assessment.projectRequired")], ["title", t("assessment.titleRequired")]] : wizardStep === 2 ? [["code", t("assessment.codeRequired")]] : [];
    const missing = required.find(([name]) => !String(values?.get(name) ?? "").trim());
    if (missing) { setError(t("assessment.validationEnter", { field: missing[1] })); return false; }
    setError(""); return true;
  }
  function nextWizardStep() { if (validateWizardStep()) setWizardStep((step) => Math.min(3, step + 1)); }
  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const formElement = event.currentTarget; const payload = fmeaPayloadFromForm(formElement);
    if (!navigator.onLine) { await setDraft(draftKey, payload); setDraftNotice(t("assessment.draftSavedOffline")); setDraftSyncAvailable(true); return; }
    try { await api("/fmea", { method: "POST", body: JSON.stringify(payload) }); await deleteDraft(draftKey); formElement.reset(); setDraftState(null); setWizardStep(1); setLastSaved(null); state.reload(); setDraftNotice(t("assessment.created", { type: "FMEA" })); setDraftSyncAvailable(false); } catch (reason) { setError((reason as Error).message); }
  }
  async function syncDraft() { const value = await getDraft(draftKey); if (!value) return; try { await api("/fmea", { method: "POST", body: JSON.stringify(fmeaPayloadFromDraft(value)) }); await deleteDraft(draftKey); setDraftState(null); setWizardStep(1); setDraftNotice(t("assessment.synced", { type: "FMEA" })); setDraftSyncAvailable(false); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function editAssessment(item: Fmea) { const title = (await dialog.prompt(t("assessment.editTitle"), item.title))?.trim(); if (!title || title === item.title) return; try { await api(`/fmea/${item.id}`, { method: "PATCH", body: JSON.stringify({ title }) }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function deleteAssessment(item: Fmea) { if (!(await dialog.confirm(t("assessment.deleteConfirm", { title: item.title })))) return; try { await api(`/fmea/${item.id}`, { method: "DELETE" }); if (selected === item.id) setSelected(""); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function loadHistory(id: string) { try { const result = await api<VersionRow[]>(`/fmea/${id}/history`); setHistory(result.data); setHistoryAssessment(id); } catch (reason) { setError((reason as Error).message); } }
  async function addItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setError(""); const formElement = event.currentTarget; const form = new FormData(formElement); const numeric = (name: string) => Number(form.get(name)); try { await api(`/fmea/${selected}/items`, { method: "POST", body: JSON.stringify({ rowNumber: numeric("rowNumber"), processStep: form.get("processStep"), failureMode: form.get("failureMode"), effect: form.get("effect"), cause: form.get("cause"), preventiveControls: form.get("preventiveControls") || null, detectionControls: form.get("detectionControls") || null, severity: numeric("severity"), occurrence: numeric("occurrence"), detection: numeric("detection"), recommendation: form.get("recommendation") || null }) }); await clearAutoSaveDraft(itemDraftKey); formElement.reset(); setScores({ severity: 1, occurrence: 1, detection: 1 }); state.reload(); } catch (reason) { setError((reason as Error).message); } }

  return <section className="page-shell">
    <PageHeader eyebrow={t("assessment.fmeaEyebrow")} title={t("assessment.fmeaTitle")} description={t("assessment.fmeaDescription")}/>
    {error && <div className="alert error" role="alert"><Icon name="warning"/>{error}</div>}
    {draftNotice && <div className="alert info" role="status"><Icon name="files"/>{draftNotice}{navigator.onLine && draftSyncAvailable && <button type="button" className="text-button" onClick={() => void syncDraft()}>{t("common.sync")}</button>}</div>}
    {canEdit() && <SectionCard title={t("assessment.evaluateNew", { type: "FMEA" })} description={t("assessment.threeSteps", { steps: t("assessment.stepBaseScopeReview") })} icon="plus">
      <form ref={formRef} className="assessment-wizard" key={draft ? "restored-draft" : "new-draft"} onInput={(event) => queueDraft(event.currentTarget, draftKey, saveTimer, setLastSaved)} onSubmit={create}>
        <div className="wizard-stepper" aria-label={t("assessment.stepsLabel", { type: "FMEA" })}>{[t("assessment.basicInfo"), t("assessment.details"), t("assessment.review")].map((label, index) => <span className={wizardStep === index + 1 ? "current" : wizardStep > index + 1 ? "done" : ""} key={label}><b>{wizardStep > index + 1 ? "✓" : index + 1}</b>{label}</span>)}</div>
        <fieldset hidden={wizardStep !== 1}><legend>{t("assessment.basicInfo")}</legend><div className="assessment-create"><label>{t("assessment.projectRequired")} <span className="required-label">{t("common.required")}</span><select name="projectId" defaultValue={draftValue(draft, "projectId")} required><option value="">{t("assessment.projectSelect")}</option>{projects.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t("assessment.titleRequired")} <span className="required-label">{t("common.required")}</span><input name="title" defaultValue={draftValue(draft, "title")} placeholder={t("assessment.titleFmeaPlaceholder")} required/></label></div></fieldset>
        <fieldset hidden={wizardStep !== 2}><legend>{t("assessment.assessmentInfo")}</legend><div className="assessment-create"><label>{t("assessment.codeRequired")} <span className="required-label">{t("common.required")}</span><input name="code" defaultValue={draftValue(draft, "code")} placeholder={t("assessment.codePlaceholder")} required/></label><label>{t("assessment.scope")} <span className="optional-label">{t("common.optional")}</span><input name="scope" defaultValue={draftValue(draft, "scope")} placeholder={t("assessment.scopePlaceholder")}/></label></div></fieldset>
        <fieldset hidden={wizardStep !== 3}><legend>{t("assessment.review")}</legend><div className="wizard-review"><Icon name="check" size={25}/><div><strong>{t("assessment.reviewReadyFmea")}</strong><p>{t("assessment.reviewFmeaDescription")}</p></div></div></fieldset>
        <div className="wizard-actions"><button className="ghost" type="button" disabled={wizardStep === 1} onClick={() => { setError(""); setWizardStep((step) => Math.max(1, step - 1)); }}>{t("common.back")}</button>{wizardStep < 3 ? <button className="primary" type="button" onClick={nextWizardStep}>{t("common.next")} <Icon name="arrow"/></button> : <button className="primary" type="submit"><Icon name="plus"/> {t("assessment.createFmea")}</button>}</div><AutoSaveStatus lastSaved={lastSaved}/>
      </form>
    </SectionCard>}
    <SectionCard title={t("assessment.registered")} description={t("assessment.registeredDescription")} icon="fmea"><LoadState state={state} empty={t("assessment.noFmea")}>{(data) => <div className="assessment-list">{data.map((item) => { const maxRpn = Math.max(0, ...item.items.map((row) => row.rpn)); return <button type="button" className={`assessment-card ${selected === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelected(item.id)}><div className="assessment-card-head"><span className="project-code">{item.code}</span><StatusBadge value={item.status}/></div><h3>{item.title}</h3><p>{projectName(item.project, locale)}{item.scope ? ` · ${item.scope}` : ""}</p><div className="assessment-metrics"><span><b>{item.items.length.toLocaleString(numberLocale)}</b> {t("assessment.riskRowCount")}</span><span><b>{maxRpn.toLocaleString(numberLocale)}</b> {t("assessment.maxRpn")}</span><span><b>{item.version.toLocaleString(numberLocale)}</b> {t("common.version")}</span></div>{canEdit() && <div className="card-actions"><span onClick={(event) => { event.stopPropagation(); void editAssessment(item); }}><Icon name="activity" size={16}/> {t("assessment.edit")}</span><span onClick={(event) => { event.stopPropagation(); void loadHistory(item.id); }}><Icon name="clock" size={16}/> {t("assessment.history")}</span><span title={t("assessment.downloadPdf")} onClick={(event) => { event.stopPropagation(); void saveBlob(`/reports/fmea/${item.id}.pdf`, `${item.code}.pdf`).catch((reason) => setError((reason as Error).message)); }}><Icon name="download" size={16}/> PDF</span><span title={t("assessment.downloadExcel")} onClick={(event) => { event.stopPropagation(); void saveBlob(`/reports/fmea/${item.id}.xlsx`, `${item.code}.xlsx`).catch((reason) => setError((reason as Error).message)); }}><Icon name="download" size={16}/> Excel</span><span className="danger-link" onClick={(event) => { event.stopPropagation(); void deleteAssessment(item); }}><Icon name="trash" size={16}/> {t("common.delete")}</span></div>}</button>; })}</div>}</LoadState></SectionCard>
    {historyAssessment && <SectionCard title={t("assessment.history")} description={t("assessment.historyDescription")} icon="clock" actions={<button className="text-button" onClick={() => setHistoryAssessment("")}>{t("assessment.historyClose")}</button>}><div className="history-list">{history.length ? history.map((version) => <div className="history-row" key={version.id}><strong>{t("common.version")} {version.version.toLocaleString(numberLocale)}</strong><span>{formatDate(version.createdAt, true)}</span></div>) : <EmptyState title={t("assessment.noHistory")} icon="clock"/>}</div></SectionCard>}
    {selectedAssessment && <SectionCard title={t("assessment.riskRows", { title: selectedAssessment.title })} description={t("assessment.riskRowsDescription")} icon="chart">{!selectedAssessment.items.length ? <EmptyState title={t("assessment.noRiskRows")} description={t("assessment.addFirstRisk")} icon="fmea"/> : <div className="table-wrap"><table><thead><tr><th>{t("assessment.row")}</th><th>{t("assessment.processStep")}</th><th>{t("assessment.failureMode")}</th><th>{t("assessment.effect")}</th><th>S</th><th>O</th><th>D</th><th>RPN</th><th>{t("assessment.riskLevel")}</th><th>{t("assessment.operations")}</th></tr></thead><tbody>{selectedAssessment.items.map((row) => <tr key={row.id}><td>{row.rowNumber.toLocaleString(numberLocale)}</td><td>{row.processStep}</td><td><strong>{row.failureMode}</strong><small>{row.cause}</small></td><td>{row.effect}</td><td>{row.severity}</td><td>{row.occurrence}</td><td>{row.detection}</td><td><strong className="rpn-number">{row.rpn.toLocaleString(numberLocale)}</strong></td><td><StatusBadge value={row.riskLevel}/></td><td><button className="icon-button danger" title={t("assessment.deleteRow")} onClick={() => void dialog.confirm(t("assessment.deleteRowConfirm")).then((confirmed) => { if (confirmed) return api(`/fmea/${selected}/items/${row.id}`, { method: "DELETE" }).then(() => state.reload()); }).catch((reason) => setError((reason as Error).message))}><Icon name="trash" size={16}/></button></td></tr>)}</tbody></table></div>}</SectionCard>}
    {selectedAssessment && canEdit() && <SectionCard title={t("assessment.addRiskRow")} description={t("assessment.scoreDescription")} icon="plus"><AutoSaveForm storageKey={itemDraftKey} className="fmea-item-form" onSubmit={addItem}><div className="form-grid three"><label>{t("assessment.rowNumber")} <span className="required-label">{t("common.required")}</span><input name="rowNumber" type="number" min="1" placeholder="1" required/></label><label>{t("assessment.processStep")} <span className="required-label">{t("common.required")}</span><input name="processStep" placeholder={t("assessment.processStepPlaceholder")} required/></label><label>{t("assessment.failureMode")} <span className="required-label">{t("common.required")}</span><input name="failureMode" placeholder={t("assessment.failureModePlaceholder")} required/></label><label>{t("assessment.effect")} <span className="required-label">{t("common.required")}</span><input name="effect" placeholder={t("assessment.effectPlaceholder")} required/></label><label>{t("assessment.cause")} <span className="required-label">{t("common.required")}</span><input name="cause" placeholder={t("assessment.causePlaceholder")} required/></label><label>{t("assessment.preventiveControls")} <span className="optional-label">{t("common.optional")}</span><input name="preventiveControls" placeholder={t("assessment.existingControls")}/></label><label>{t("assessment.detectionControls")} <span className="optional-label">{t("common.optional")}</span><input name="detectionControls" placeholder={t("assessment.detectionPlaceholder")}/></label><label className="span-two">{t("assessment.recommendation")} <span className="optional-label">{t("common.optional")}</span><textarea name="recommendation" rows={2} placeholder={t("assessment.recommendationPlaceholder")}/></label></div><div className="score-panel"><label>{t("assessment.severity")}<input name="severity" type="number" min="1" max="10" value={scores.severity} onChange={(event) => setScores((value) => ({ ...value, severity: Number(event.target.value) }))} required/></label><span>×</span><label>{t("assessment.occurrence")}<input name="occurrence" type="number" min="1" max="10" value={scores.occurrence} onChange={(event) => setScores((value) => ({ ...value, occurrence: Number(event.target.value) }))} required/></label><span>×</span><label>{t("assessment.detection")}<input name="detection" type="number" min="1" max="10" value={scores.detection} onChange={(event) => setScores((value) => ({ ...value, detection: Number(event.target.value) }))} required/></label><div className="rpn-preview"><small>{t("assessment.calculatedRpn")}</small><strong>{previewRpn.toLocaleString(numberLocale)}</strong></div><button className="primary"><Icon name="plus"/> {t("assessment.calculateRegister")}</button></div></AutoSaveForm></SectionCard>}
  </section>;
}

const rulaFields = [["upperArm", "assessment.upperArm", "assessment.upperArmHint"], ["lowerArm", "assessment.lowerArm", "assessment.lowerArmHint"], ["wrist", "assessment.wrist", "assessment.wristHint"], ["wristTwist", "assessment.wristTwist", "assessment.wristTwistHint"], ["neck", "assessment.neck", "assessment.neckHint"], ["trunk", "assessment.trunk", "assessment.trunkHint"], ["legs", "assessment.legs", "assessment.legsHint"]] as const;

function rulaPayloadFromForm(form: HTMLFormElement) { const values = new FormData(form); const inputs = Object.fromEntries(rulaFields.map(([key]) => [key, Number(values.get(key))])); return { projectId: values.get("projectId"), title: values.get("title"), subjectCode: values.get("subjectCode") || null, bodySide: values.get("bodySide"), inputs: { ...inputs, muscleUse: values.get("muscleUse") === "on", force: Number(values.get("force")) } }; }
function rulaPayloadFromDraft(value: unknown) { const draft = (value && typeof value === "object" ? value : {}) as DraftRecord; const number = (key: string, fallback: number) => Number(draft[key] ?? fallback); return { projectId: draft.projectId ?? "", title: draft.title ?? "", subjectCode: draft.subjectCode || null, bodySide: draft.bodySide === "LEFT" ? "LEFT" : "RIGHT", inputs: { upperArm: number("upperArm", 2), lowerArm: number("lowerArm", 2), wrist: number("wrist", 2), wristTwist: number("wristTwist", 2), neck: number("neck", 2), trunk: number("trunk", 2), legs: number("legs", 2), muscleUse: draft.muscleUse === true || draft.muscleUse === "on" || draft.muscleUse === "true", force: number("force", 0) } }; }

export function RulaPage() {
  const { locale, t } = useI18n();
  const numberLocale = locale === "en" ? "en-US" : "fa-IR";
  const assessmentLabel = "RULA"; const draftKey = draftKeyFor("rula"); const state = useLoad<Rula[]>("/rula"); const projects = useLoad<Project[]>("/projects"); const [error, setError] = useState(""); const [draftNotice, setDraftNotice] = useState(""); const [draftSyncAvailable, setDraftSyncAvailable] = useState(false); const [history, setHistory] = useState<VersionRow[]>([]); const [historyAssessment, setHistoryAssessment] = useState(""); const [wizardStep, setWizardStep] = useState(1); const [draft, setDraftState] = useState<DraftRecord | null>(null); const [lastSaved, setLastSaved] = useState<Date | null>(null); const dialog = useDialog(); const formRef = useRef<HTMLFormElement>(null); const saveTimer = useRef<number | null>(null);
  const overview = useMemo(() => ({ total: state.data?.length ?? 0, high: state.data?.filter((x) => x.actionLevel >= 3).length ?? 0, average: state.data?.length ? Math.round(state.data.reduce((sum, item) => sum + item.score, 0) / state.data.length) : 0 }), [state.data]);
  useEffect(() => { void getDraft(draftKey).then((value) => { if (value && typeof value === "object") { setDraftState(value as DraftRecord); setDraftNotice(t("assessment.draftAvailable", { type: assessmentLabel })); setDraftSyncAvailable(true); } }); return () => { if (saveTimer.current !== null) window.clearTimeout(saveTimer.current); }; }, [assessmentLabel, draftKey, locale]);
  function validateWizardStep() { const values = formRef.current ? new FormData(formRef.current) : null; const required = wizardStep === 1 ? [["projectId", t("assessment.projectRequired")], ["title", t("assessment.titleRequired")]] : []; const missing = required.find(([name]) => !String(values?.get(name) ?? "").trim()); if (missing) { setError(t("assessment.validationEnter", { field: missing[1] })); return false; } setError(""); return true; }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const element = event.currentTarget; const payload = rulaPayloadFromForm(element); setError(""); if (!navigator.onLine) { await setDraft(draftKey, payload); setDraftNotice(t("assessment.draftSavedOffline")); setDraftSyncAvailable(true); return; } try { await api("/rula", { method: "POST", body: JSON.stringify(payload) }); await deleteDraft(draftKey); element.reset(); setDraftState(null); setWizardStep(1); setLastSaved(null); state.reload(); setDraftNotice(t("assessment.created", { type: assessmentLabel })); setDraftSyncAvailable(false); } catch (reason) { setError((reason as Error).message); } }
  async function syncDraft() { const value = await getDraft(draftKey); if (!value) return; try { await api("/rula", { method: "POST", body: JSON.stringify(rulaPayloadFromDraft(value)) }); await deleteDraft(draftKey); setDraftState(null); setWizardStep(1); setDraftNotice(t("assessment.synced", { type: assessmentLabel })); setDraftSyncAvailable(false); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function editAssessment(item: Rula) { const title = (await dialog.prompt(t("assessment.editTitle"), item.title))?.trim(); if (!title || title === item.title) return; try { await api(`/rula/${item.id}`, { method: "PATCH", body: JSON.stringify({ title }) }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function deleteAssessment(item: Rula) { if (!(await dialog.confirm(t("assessment.deleteConfirm", { title: item.title })))) return; try { await api(`/rula/${item.id}`, { method: "DELETE" }); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function loadHistory(id: string) { try { const result = await api<VersionRow[]>(`/rula/${id}/history`); setHistory(result.data); setHistoryAssessment(id); } catch (reason) { setError((reason as Error).message); } }

  return <section className="page-shell">
    <PageHeader eyebrow={t("assessment.rulaEyebrow")} title={t("assessment.rulaTitle")} description={t("assessment.rulaDescription")}/>
    {error && <div className="alert error" role="alert"><Icon name="warning"/>{error}</div>}
    {draftNotice && <div className="alert info" role="status"><Icon name="files"/>{draftNotice}{navigator.onLine && draftSyncAvailable && <button type="button" className="text-button" onClick={() => void syncDraft()}>{t("common.sync")}</button>}</div>}
    <div className="mini-stats"><div><Icon name="rula"/><strong>{overview.total.toLocaleString(numberLocale)}</strong><span>{t("assessment.assessmentCount")}</span></div><div><Icon name="warning"/><strong>{overview.high.toLocaleString(numberLocale)}</strong><span>{t("assessment.needsAction")}</span></div><div><Icon name="chart"/><strong>{overview.average.toLocaleString(numberLocale)}</strong><span>{t("assessment.averageScore")}</span></div></div>
    {canEdit() && <SectionCard title={t("assessment.evaluateNew", { type: assessmentLabel })} description={t("assessment.threeSteps", { steps: t("assessment.stepBaseScoreReview") })} icon="plus">
      <form ref={formRef} className="rula-form assessment-wizard" key={draft ? "restored-draft" : "new-draft"} onInput={(event) => queueDraft(event.currentTarget, draftKey, saveTimer, setLastSaved)} onSubmit={create}>
        <div className="wizard-stepper" aria-label={t("assessment.stepsLabel", { type: assessmentLabel })}>{[t("assessment.basicInfo"), t("assessment.bodyScoring"), t("assessment.review")].map((label, index) => <span className={wizardStep === index + 1 ? "current" : wizardStep > index + 1 ? "done" : ""} key={label}><b>{wizardStep > index + 1 ? "✓" : index + 1}</b>{label}</span>)}</div>
        <fieldset hidden={wizardStep !== 1}><legend>{t("assessment.basicInfo")}</legend><div className="rula-basic"><label>{t("assessment.projectRequired")} <span className="required-label">{t("common.required")}</span><select name="projectId" defaultValue={draftValue(draft, "projectId")} required><option value="">{t("assessment.projectSelect")}</option>{projects.data?.map((project) => <option key={project.id} value={project.id}>{projectName(project, locale)}</option>)}</select></label><label>{t("assessment.titleRequired")} <span className="required-label">{t("common.required")}</span><input name="title" defaultValue={draftValue(draft, "title")} placeholder={t("assessment.titleRulaPlaceholder")} required/></label><label>{t("assessment.subjectCode")} <span className="optional-label">{t("common.optional")}</span><input name="subjectCode" defaultValue={draftValue(draft, "subjectCode")} placeholder={t("assessment.subjectCodePlaceholder")}/></label><label>{t("assessment.bodySide")}<select name="bodySide" defaultValue={draftValue(draft, "bodySide", "RIGHT")}><option value="RIGHT">{t("assessment.right")}</option><option value="LEFT">{t("assessment.left")}</option></select></label></div></fieldset>
        <fieldset hidden={wizardStep !== 2}><legend>{t("assessment.bodyScoring")}</legend><div className="body-score-grid">{rulaFields.map(([field, labelKey, hintKey]) => <label className="body-score" key={field}><span><strong>{t(labelKey)}</strong><small>{t(hintKey)}</small></span><input name={field} type="number" min="1" max="6" defaultValue={draftValue(draft, field, "2")} required/></label>)}</div><div className="rula-extra"><label>{t("assessment.force")} <span className="required-label">{t("common.required")}</span><select name="force" defaultValue={draftValue(draft, "force", "0")}><option value="0">{t("assessment.noSignificantForce")}</option><option value="1">{t("assessment.lowForce")}</option><option value="2">{t("assessment.mediumForce")}</option><option value="3">{t("assessment.highForce")}</option></select></label><label className="checkbox-card"><input name="muscleUse" type="checkbox" defaultChecked={draft?.muscleUse === true || draft?.muscleUse === "on" || draft?.muscleUse === "true"}/><span><strong>{t("assessment.repetitiveMuscle")}</strong><small>{t("assessment.repetitiveMuscleHint")}</small></span></label></div></fieldset>
        <fieldset hidden={wizardStep !== 3}><legend>{t("assessment.review")}</legend><div className="wizard-review"><Icon name="check" size={25}/><div><strong>{t("assessment.reviewReadyRula")}</strong><p>{t("assessment.reviewRulaDescription")}</p></div></div></fieldset>
        <div className="wizard-actions"><button className="ghost" type="button" disabled={wizardStep === 1} onClick={() => { setError(""); setWizardStep((step) => Math.max(1, step - 1)); }}>{t("common.back")}</button>{wizardStep < 3 ? <button className="primary" type="button" onClick={() => { if (validateWizardStep()) setWizardStep((step) => Math.min(3, step + 1)); }}>{t("common.next")} <Icon name="arrow"/></button> : <button className="primary" type="submit"><Icon name="chart"/> {t("assessment.calculateRegisterRula")}</button>}</div><AutoSaveStatus lastSaved={lastSaved}/>
      </form>
    </SectionCard>}
    <SectionCard title={t("assessment.rulaResults")} description={t("assessment.rulaResultsDescription")} icon="chart"><LoadState state={state} empty={t("assessment.noRula")}>{(data) => <div className="rula-results">{data.map((item) => <article className="rula-result" key={item.id}><div className={"rula-score level-" + item.actionLevel}>{item.score.toLocaleString(numberLocale)}</div><div className="rula-result-copy"><div><h3>{item.title}</h3><p>{projectName(item.project, locale)}{item.subjectCode ? " · " + item.subjectCode : ""}</p></div><div className="result-badges"><StatusBadge value={item.status}/><span className="action-level">{t("assessment.actionLevel", { level: item.actionLevel.toLocaleString(numberLocale) })}</span></div><small>{item.explanation}</small></div>{canEdit() && <div className="download-actions"><button className="ghost" onClick={() => void editAssessment(item)}><Icon name="activity"/> {t("assessment.edit")}</button><button className="ghost" onClick={() => void loadHistory(item.id)}><Icon name="clock"/> {t("assessment.history")}</button><button className="ghost" title={t("assessment.downloadPdf")} onClick={() => void saveBlob("/reports/rula/" + item.id + ".pdf", assessmentLabel + "-" + item.id + ".pdf").catch((reason) => setError((reason as Error).message))}><Icon name="download"/> PDF</button><button className="ghost" title={t("assessment.downloadExcel")} onClick={() => void saveBlob("/reports/rula/" + item.id + ".xlsx", assessmentLabel + "-" + item.id + ".xlsx").catch((reason) => setError((reason as Error).message))}><Icon name="download"/> Excel</button><button className="ghost danger-button" onClick={() => void deleteAssessment(item)}><Icon name="trash"/> {t("common.delete")}</button></div>}</article>)}</div>}</LoadState></SectionCard>
    {historyAssessment && <SectionCard title={t("assessment.history")} description={t("assessment.historyDescription")} icon="clock" actions={<button className="text-button" onClick={() => setHistoryAssessment("")}>{t("assessment.historyClose")}</button>}><div className="history-list">{history.length ? history.map((version) => <div className="history-row" key={version.id}><strong>{t("common.version")} {version.version.toLocaleString(numberLocale)}</strong><span>{formatDate(version.createdAt, true)}</span></div>) : <EmptyState title={t("assessment.noHistory")} icon="clock"/>}</div></SectionCard>}
  </section>;
}
