import { useState, type FormEvent } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { api, clearSession, getSession, saveSession, type Organization, type Session, useLoad } from "../../api/client";
import { EmptyState, Icon, PageHeader, SectionCard, roleLabel } from "../../components/UI";

type Profile = { id: string; email: string; displayName: string; locale: string; phone: string | null; jobTitle: string | null };
type Member = { id: string; role: string; active: boolean; user: { id: string; email: string; displayName: string } };
const roles = ["ORG_ADMIN", "HSE_MANAGER", "ASSESSOR", "VIEWER"];

export function LoginPage() {
  const demoEmail = import.meta.env.DEV ? "admin@nivasafe.local" : undefined;
  const demoPassword = import.meta.env.DEV ? "Demo123!" : undefined;
  const nav = useNavigate(); const [params] = useSearchParams(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); setError(""); try { const result = await api<Session>("/auth/login", { method: "POST", body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); saveSession(result.data); const next = params.get("next"); nav(next?.startsWith("/") ? next : "/"); } catch (reason) { setError((reason as Error).message); } finally { setLoading(false); } }
  return <main className="login" dir="rtl"><section className="login-art"><div className="brand-mark">N</div><h1>NIVASafe</h1><p>سامانه یکپارچه مدیریت ارزیابی ریسک، ارگونومی و اقدامات اصلاحی سازمان</p><div className="login-features"><span><Icon name="shield"/> مدیریت امن داده‌های HSE</span><span><Icon name="chart"/> تحلیل ریسک و گزارش مدیریتی</span><span><Icon name="assistant"/> دستیار هوشمند مبتنی بر دانش سازمان</span></div></section><form className="login-card" onSubmit={submit}><div className="eyebrow">سامانه مدیریت HSE</div><h2>خوش آمدید</h2><p className="muted">برای ورود به فضای کاری سازمان، اطلاعات حساب خود را وارد کنید.</p><label>ایمیل<input name="email" type="email" defaultValue={demoEmail} autoComplete="username" required/></label><label>رمز عبور<input name="password" type="password" defaultValue={demoPassword} autoComplete="current-password" required/></label>{error && <div className="alert error"><Icon name="warning"/>{error}</div>}<button className="primary login-button" disabled={loading}>{loading ? "در حال ورود…" : <><Icon name="shield"/> ورود امن</>}</button><Link className="login-link" to="/forgot-password">رمز عبور را فراموش کرده‌ام</Link>{import.meta.env.DEV && <small className="login-hint">حساب نمایشی فقط در محیط توسعه ایجاد می‌شود.</small>}</form></main>;
}

export function ForgotPasswordPage() {
  const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await api<{ accepted: boolean; developmentToken?: string }>("/auth/forgot-password", { method: "POST", body: JSON.stringify({ email: form.get("email") }) }); setMessage(result.data.developmentToken ? `درخواست ثبت شد. توکن توسعه: ${result.data.developmentToken}` : "در صورت وجود حساب، لینک بازیابی ارسال می‌شود."); } catch (reason) { setError((reason as Error).message); } }
  return <main className="login simple" dir="rtl"><form className="login-card" onSubmit={submit}><span className="auth-icon"><Icon name="profile" size={28}/></span><div className="eyebrow">بازیابی حساب</div><h2>فراموشی رمز عبور</h2><p className="muted">ایمیل حساب را وارد کنید تا فرایند بازیابی آغاز شود.</p><label>ایمیل<input name="email" type="email" required/></label>{error && <div className="alert error">{error}</div>}{message && <div className="alert success">{message}</div>}<button className="primary">ارسال درخواست</button><Link className="login-link" to="/login">بازگشت به ورود</Link></form></main>;
}
export function ResetPasswordPage() {
  const [params] = useSearchParams(); const nav = useNavigate(); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api("/auth/reset-password", { method: "POST", body: JSON.stringify({ token: params.get("token") || form.get("token"), password: form.get("password") }) }); nav("/login"); } catch (reason) { setError((reason as Error).message); } }
  return <main className="login simple" dir="rtl"><form className="login-card" onSubmit={submit}><span className="auth-icon"><Icon name="shield" size={28}/></span><h2>تنظیم رمز جدید</h2>{!params.get("token") && <label>توکن بازیابی<input name="token" required/></label>}<label>رمز جدید<input name="password" type="password" minLength={8} required/></label>{error && <div className="alert error">{error}</div>}<button className="primary">ثبت رمز جدید</button></form></main>;
}

export function AcceptInvitationPage() {
  const [params] = useSearchParams(); const nav = useNavigate(); const token = params.get("token") ?? ""; const { session } = getSession(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function accept() { if (!session || !token) return; setLoading(true); setError(""); try { const result = await api<{ organization: Organization }>("/invitations/accept", { method: "POST", body: JSON.stringify({ token }) }); const organizations = [...session.organizations.filter((item) => item.id !== result.data.organization.id), result.data.organization]; saveSession({ ...session, organizations }); localStorage.setItem("nivasafe-org", result.data.organization.id); nav("/", { replace: true }); } catch (reason) { setError((reason as Error).message); } finally { setLoading(false); } }
  if (!token) return <main className="login simple" dir="rtl"><section className="login-card"><div className="alert error">توکن دعوت در لینک وجود ندارد.</div><Link className="login-link" to="/login">بازگشت به ورود</Link></section></main>;
  if (!session) { const next = `/accept-invitation?token=${encodeURIComponent(token)}`; return <main className="login simple" dir="rtl"><section className="login-card"><span className="auth-icon"><Icon name="members" size={28}/></span><h2>پذیرش دعوت سازمان</h2><p className="muted">برای پذیرش دعوت ابتدا با همان ایمیلی که دعوت شده وارد شوید.</p><Link className="primary button-link" to={`/login?next=${encodeURIComponent(next)}`}>ورود و ادامه</Link></section></main>; }
  return <main className="login simple" dir="rtl"><section className="login-card"><span className="auth-icon"><Icon name="members" size={28}/></span><h2>پذیرش دعوت سازمان</h2><p className="muted">با تأیید، سازمان جدید به فضای کاری شما اضافه می‌شود.</p>{error && <div className="alert error">{error}</div>}<button className="primary" onClick={accept} disabled={loading}>{loading ? "در حال ثبت…" : "پذیرش دعوت"}</button></section></main>;
}

export function ProfilePage() {
  const nav = useNavigate();
  const state = useLoad<Profile>("/profile"); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  if (state.error) return <div className="alert error">{state.error}</div>; if (!state.data) return <div className="state"><div className="spinner"/></div>;
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); try { await api("/profile", { method: "PATCH", body: JSON.stringify({ displayName: form.get("displayName"), phone: form.get("phone") || null, jobTitle: form.get("jobTitle") || null, locale: form.get("locale") }) }); setMessage("پروفایل ذخیره شد."); state.reload(); } catch (reason) { setError((reason as Error).message); } }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setError(""); try { await api("/profile/change-password", { method: "POST", body: JSON.stringify({ currentPassword: form.get("currentPassword"), newPassword: form.get("newPassword") }) }); formElement.reset(); clearSession(); nav("/login", { replace: true }); } catch (reason) { setError((reason as Error).message); } }
  return <section className="page-shell"><PageHeader eyebrow="حساب کاربری" title="پروفایل من" description="اطلاعات فردی، زبان رابط و رمز عبور حساب را مدیریت کنید."/>{error && <div className="alert error"><Icon name="warning"/>{error}</div>}{message && <div className="alert success"><Icon name="check"/>{message}</div>}
    <div className="profile-hero"><div className="profile-avatar">{state.data.displayName[0]}</div><div><h3>{state.data.displayName}</h3><p>{state.data.jobTitle || "عنوان شغلی ثبت نشده"}</p><span>{state.data.email}</span></div></div>
    <div className="form-panels"><SectionCard title="اطلاعات فردی" description="مشخصات نمایشی حساب شما" icon="profile"><form className="form-grid" onSubmit={save}><label>نام نمایشی<input name="displayName" defaultValue={state.data.displayName} required/></label><label>ایمیل<input value={state.data.email} disabled/></label><label>تلفن<input name="phone" defaultValue={state.data.phone ?? ""} placeholder="شماره تماس"/></label><label>عنوان شغلی<input name="jobTitle" defaultValue={state.data.jobTitle ?? ""} placeholder="مثلاً مدیر HSE"/></label><label className="full">زبان رابط<select name="locale" defaultValue={state.data.locale}><option value="fa">فارسی</option><option value="en">English</option></select></label><button className="primary full"><Icon name="check"/> ذخیره تغییرات</button></form></SectionCard>
    <SectionCard title="تغییر رمز عبور" description="رمز جدید باید حداقل ۸ کاراکتر باشد." icon="shield"><form className="form-grid" onSubmit={changePassword}><label className="full">رمز فعلی<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label className="full">رمز جدید<input name="newPassword" type="password" minLength={8} autoComplete="new-password" required/></label><div className="password-note full"><Icon name="shield"/><span>پس از تغییر رمز، نشست‌های قبلی برای حفظ امنیت باطل می‌شوند.</span></div><button className="primary full">تغییر رمز عبور</button></form></SectionCard></div>
  </section>;
}

export function MembersPage() {
  const state = useLoad<Member[]>("/members"); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function update(id: string, role: string, active: boolean) { try { await api(`/members/${id}`, { method: "PATCH", body: JSON.stringify({ role, active }) }); state.reload(); setMessage("دسترسی عضو به‌روزرسانی شد."); } catch (reason) { setError((reason as Error).message); } }
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); try { const result = await api<{ developmentToken?: string }>("/invitations", { method: "POST", body: JSON.stringify({ email: form.get("email"), role: form.get("role") }) }); setMessage(result.data.developmentToken ? `دعوت ایجاد شد. توکن توسعه: ${result.data.developmentToken}` : "دعوت ارسال شد."); element.reset(); } catch (reason) { setError((reason as Error).message); } }
  return <section className="page-shell"><PageHeader eyebrow="کنترل دسترسی" title="اعضا و نقش‌ها" description="اعضای سازمان را دعوت کنید و سطح دسترسی هر کاربر را مدیریت کنید."/>{error && <div className="alert error"><Icon name="warning"/>{error}</div>}{message && <div className="alert success"><Icon name="check"/>{message}</div>}
    <SectionCard title="دعوت عضو جدید" description="یک نقش اولیه برای عضو انتخاب کنید؛ پس از عضویت قابل تغییر است." icon="plus"><form className="invite-form" onSubmit={invite}><label>ایمیل عضو<input name="email" type="email" placeholder="name@company.com" required/></label><label>نقش<select name="role">{roles.map((role) => <option key={role} value={role}>{roleLabel(role)}</option>)}</select></label><button className="primary"><Icon name="plus"/> ارسال دعوت</button></form></SectionCard>
    <SectionCard title="اعضای سازمان" description={`${(state.data?.length ?? 0).toLocaleString("fa-IR")} عضو`} icon="members">{state.loading ? <div className="state"><div className="spinner"/></div> : !state.data?.length ? <EmptyState title="هنوز عضوی ثبت نشده است" icon="members"/> : <div className="member-list">{state.data.map((member) => <article className="member-card" key={member.id}><div className="member-avatar">{member.user.displayName[0]}</div><div className="member-copy"><strong>{member.user.displayName}</strong><small>{member.user.email}</small></div><select value={member.role} onChange={(event) => update(member.id, event.target.value, member.active)}>{roles.map((role) => <option key={role} value={role}>{roleLabel(role)}</option>)}</select><button className={`status-toggle ${member.active ? "active" : "inactive"}`} onClick={() => update(member.id, member.role, !member.active)}><span/>{member.active ? "فعال" : "غیرفعال"}</button></article>)}</div>}
    </SectionCard>
  </section>;
}
