import type { FastifyInstance } from "fastify";
import { AIRequestStatus, Prisma } from "@prisma/client";
import { z } from "zod";
import { getAIProvider, getAvailableAIProvider, listAIProviders } from "../ai-provider.js";
import { authenticate } from "../auth-guard.js";
import { audit, envelope, pageParams, parse, prisma, requireOrg } from "../core.js";
import { enqueueAI } from "../queue.js";

const analysisSchema = z.object({ type: z.string().min(2).default("GENERAL"), provider: z.enum(["fallback", "openai", "gemini", "anthropic"]).default("fallback"), message: z.string().min(3), context: z.record(z.string(), z.unknown()).optional() });
const keyAvailable = (provider: string) => getAIProvider(provider).available();

async function runInline(id: string, organizationId: string, userId: string, providerName: string, message: string) {
  if (!keyAvailable(providerName)) { await prisma.aIAnalysisRequest.update({ where: { id }, data: { status: AIRequestStatus.WAITING_FOR_PROVIDER, error: `${providerName} is not configured`, attempts: { increment: 1 } } }); return; }
  try { await prisma.aIAnalysisRequest.update({ where: { id }, data: { status: AIRequestStatus.PROCESSING, startedAt: new Date(), attempts: { increment: 1 } } }); const output = await getAIProvider(providerName).analyze({ organizationId, userId, message }); await prisma.aIAnalysisRequest.update({ where: { id }, data: { status: AIRequestStatus.SUCCEEDED, output: output as unknown as Prisma.InputJsonValue, provider: output.provider, completedAt: new Date(), error: null } }); }
  catch (error) { await prisma.aIAnalysisRequest.update({ where: { id }, data: { status: AIRequestStatus.WAITING_FOR_PROVIDER, error: error instanceof Error ? error.message : "Provider unavailable" } }); }
}

export async function registerAIRoutes(app: FastifyInstance) {
  app.get("/api/v1/ai/providers", { preHandler: authenticate }, async (request) => { requireOrg(request); return envelope(listAIProviders()); });
  app.get("/api/v1/ai/requests", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); const q = pageParams(request.query); const [data, total] = await Promise.all([prisma.aIAnalysisRequest.findMany({ where: { organizationId }, skip: (q.page - 1) * q.limit, take: q.limit, orderBy: { createdAt: "desc" } }), prisma.aIAnalysisRequest.count({ where: { organizationId } })]); return envelope(data, { page: q.page, limit: q.limit, total }); });
  app.post("/api/v1/ai/requests", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); const body = parse(analysisSchema, request.body); const item = await prisma.aIAnalysisRequest.create({ data: { organizationId, userId: request.actor!.userId, type: body.type, provider: body.provider, input: body as unknown as Prisma.InputJsonValue } }); const queued = await enqueueAI(item.id); if (!queued) await runInline(item.id, organizationId, request.actor!.userId, body.provider, body.message); await audit(request, "AI_REQUEST_CREATE", "AIAnalysisRequest", item.id); return reply.code(202).send(envelope(await prisma.aIAnalysisRequest.findUniqueOrThrow({ where: { id: item.id } }))); });
  app.get("/api/v1/ai/requests/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const item = await prisma.aIAnalysisRequest.findFirst({ where: { id, organizationId } }); if (!item) throw Object.assign(new Error("AI request not found"), { statusCode: 404 }); return envelope(item); });
  app.post("/api/v1/ai/requests/:id/retry", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const item = await prisma.aIAnalysisRequest.findFirst({ where: { id, organizationId } }); if (!item) throw Object.assign(new Error("AI request not found"), { statusCode: 404 }); const input = item.input as { message?: string }; await prisma.aIAnalysisRequest.update({ where: { id }, data: { status: AIRequestStatus.PENDING, availableAt: new Date(), error: null } }); const queued = await enqueueAI(id); if (!queued) await runInline(id, organizationId, request.actor!.userId, item.provider, input.message ?? "retry"); await audit(request, "AI_REQUEST_RETRY", "AIAnalysisRequest", id); return reply.code(202).send(envelope(await prisma.aIAnalysisRequest.findUniqueOrThrow({ where: { id } }))); });

  app.get("/api/v1/chat/conversations", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); return envelope(await prisma.chatConversation.findMany({ where: { organizationId, userId: request.actor!.userId, archivedAt: null }, include: { messages: { orderBy: { createdAt: "asc" }, take: 1 } }, orderBy: { updatedAt: "desc" } })); });
  app.post("/api/v1/chat/conversations", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); const body = parse(z.object({ title: z.string().min(2), projectId: z.preprocess((value) => value === "" ? null : value, z.string().uuid().nullable().optional()) }), request.body); if (body.projectId) { const project = await prisma.project.findFirst({ where: { id: body.projectId, organizationId, deletedAt: null } }); if (!project) throw Object.assign(new Error("Project not found"), { statusCode: 404, code: "NOT_FOUND" }); } return reply.code(201).send(envelope(await prisma.chatConversation.create({ data: { organizationId, userId: request.actor!.userId, ...body } }))); });
  app.get("/api/v1/chat/conversations/:id/messages", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const conversation = await prisma.chatConversation.findFirst({ where: { id, organizationId, userId: request.actor!.userId } }); if (!conversation) throw Object.assign(new Error("Conversation not found"), { statusCode: 404 }); return envelope(await prisma.chatMessage.findMany({ where: { conversationId: id }, orderBy: { createdAt: "asc" } })); });
  app.post("/api/v1/chat/conversations/:id/messages", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const { content } = parse(z.object({ content: z.string().min(2) }), request.body); const conversation = await prisma.chatConversation.findFirst({ where: { id, organizationId, userId: request.actor!.userId } }); if (!conversation) throw Object.assign(new Error("Conversation not found"), { statusCode: 404 }); await prisma.chatMessage.create({ data: { conversationId: id, role: "user", content } }); const result = await getAvailableAIProvider().analyze({ organizationId, userId: request.actor!.userId, message: content }); const assistant = await prisma.chatMessage.create({ data: { conversationId: id, role: "assistant", content: result.answer, citations: result.citations as unknown as Prisma.InputJsonValue, provider: result.provider } }); await prisma.chatConversation.update({ where: { id }, data: { updatedAt: new Date() } }); return reply.code(201).send(envelope(assistant)); });
  app.patch("/api/v1/chat/messages/:id/feedback", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const { feedback } = parse(z.object({ feedback: z.number().int().min(-1).max(1) }), request.body); const message = await prisma.chatMessage.findFirst({ where: { id, conversation: { organizationId, userId: request.actor!.userId } } }); if (!message) throw Object.assign(new Error("Message not found"), { statusCode: 404 }); return envelope(await prisma.chatMessage.update({ where: { id }, data: { feedback } })); });
}
