import type { FastifyInstance } from "fastify";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { calculateRpn, calculateRula, riskLevel, type RulaInput } from "@nivasafe/domain";
import { authenticate } from "../auth-guard.js";
import { audit, envelope, parse, prisma, requireOrg, requirePermission } from "../core.js";

const idParam = z.object({ id: z.string().uuid() });
const nullableUuid = z.preprocess((value) => value === "" ? null : value, z.string().uuid().nullable().optional());
const fmeaBody = z.object({ projectId: z.string().uuid(), activityId: nullableUuid, title: z.string().min(2), code: z.string().min(2), scope: z.string().nullable().optional(), status: z.enum(["DRAFT", "IN_PROGRESS", "UNDER_REVIEW", "APPROVED", "REJECTED", "ARCHIVED"]).optional() });
const fmeaItemBody = z.object({ rowNumber: z.number().int().positive(), processStep: z.string().min(1), failureMode: z.string().min(1), effect: z.string().min(1), cause: z.string().min(1), preventiveControls: z.string().nullable().optional(), detectionControls: z.string().nullable().optional(), severity: z.number().int().min(1).max(10), occurrence: z.number().int().min(1).max(10), detection: z.number().int().min(1).max(10), recommendation: z.string().nullable().optional(), residualSeverity: z.number().int().min(1).max(10).nullable().optional(), residualOccurrence: z.number().int().min(1).max(10).nullable().optional(), residualDetection: z.number().int().min(1).max(10).nullable().optional() });
const rulaInputs = z.object({ upperArm: z.number().int().min(1).max(6), lowerArm: z.number().int().min(1).max(6), wrist: z.number().int().min(1).max(6), wristTwist: z.number().int().min(1).max(6), neck: z.number().int().min(1).max(6), trunk: z.number().int().min(1).max(6), legs: z.number().int().min(1).max(6), muscleUse: z.boolean(), force: z.number().int().min(0).max(3) });
const rulaBody = z.object({ projectId: z.string().uuid(), activityId: nullableUuid, title: z.string().min(2), subjectCode: z.string().nullable().optional(), bodySide: z.enum(["LEFT", "RIGHT"]), inputs: rulaInputs, status: z.enum(["DRAFT", "IN_PROGRESS", "UNDER_REVIEW", "APPROVED", "REJECTED", "ARCHIVED"]).optional() });
const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;

async function ensureProject(projectId: string, organizationId: string) {
  const project = await prisma.project.findFirst({ where: { id: projectId, organizationId, deletedAt: null } });
  if (!project) throw Object.assign(new Error("Project not found"), { statusCode: 404, code: "NOT_FOUND" });
}

async function ensureActivity(activityId: string | null | undefined, projectId: string, organizationId: string) {
  if (!activityId) return;
  const activity = await prisma.activity.findFirst({ where: { id: activityId, projectId, organizationId, deletedAt: null } });
  if (!activity) throw Object.assign(new Error("The selected activity does not belong to this project"), { statusCode: 400, code: "ACTIVITY_PROJECT_MISMATCH" });
}

async function getFmea(id: string, organizationId: string) {
  const assessment = await prisma.fmeaAssessment.findFirst({ where: { id, organizationId, deletedAt: null }, include: { items: { orderBy: { rowNumber: "asc" } }, project: true, activity: true } });
  if (!assessment) throw Object.assign(new Error("FMEA not found"), { statusCode: 404, code: "NOT_FOUND" });
  return assessment;
}

async function getRula(id: string, organizationId: string) {
  const assessment = await prisma.rulaAssessment.findFirst({ where: { id, organizationId }, include: { project: true, activity: true } });
  if (!assessment) throw Object.assign(new Error("RULA not found"), { statusCode: 404, code: "NOT_FOUND" });
  return assessment;
}

export async function registerAssessmentRoutes(app: FastifyInstance) {
  app.get("/api/v1/fmea", { preHandler: authenticate }, async (request) => envelope(await prisma.fmeaAssessment.findMany({ where: { organizationId: requireOrg(request), deletedAt: null }, include: { items: true, project: { select: { name: true, code: true } } }, orderBy: { updatedAt: "desc" } })));
  app.get("/api/v1/fmea/:id", { preHandler: authenticate }, async (request) => envelope(await getFmea(parse(idParam, request.params).id, requireOrg(request))));
  app.post("/api/v1/fmea", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.create"); const body = parse(fmeaBody, request.body); await ensureProject(body.projectId, organizationId); await ensureActivity(body.activityId, body.projectId, organizationId); const assessment = await prisma.fmeaAssessment.create({ data: { organizationId, ...body } }); await prisma.fmeaVersion.create({ data: { assessmentId: assessment.id, version: 1, snapshot: json(assessment), createdBy: request.actor!.userId } }); await audit(request, "FMEA_CREATE", "FmeaAssessment", assessment.id); return reply.code(201).send(envelope(assessment)); });
  app.patch("/api/v1/fmea/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.update"); const { id } = parse(idParam, request.params); const current = await getFmea(id, organizationId); const body = parse(fmeaBody.partial(), request.body); const projectId = body.projectId ?? current.projectId; await ensureProject(projectId, organizationId); await ensureActivity(body.activityId === undefined ? current.activityId : body.activityId, projectId, organizationId); const nextVersion = current.version + 1; const approvedAt = body.status === "APPROVED" ? new Date() : current.approvedAt; const nextSnapshot = { ...current, ...body, projectId, activityId: body.activityId === undefined ? current.activityId : body.activityId, version: nextVersion, approvedAt }; const assessment = await prisma.$transaction(async (tx) => { await tx.fmeaVersion.upsert({ where: { assessmentId_version: { assessmentId: id, version: current.version } }, update: {}, create: { assessmentId: id, version: current.version, snapshot: json(current), createdBy: request.actor!.userId } }); const updated = await tx.fmeaAssessment.update({ where: { id }, data: { ...body, version: nextVersion, approvedAt } }); await tx.fmeaVersion.upsert({ where: { assessmentId_version: { assessmentId: id, version: nextVersion } }, update: {}, create: { assessmentId: id, version: nextVersion, snapshot: json(nextSnapshot), createdBy: request.actor!.userId } }); return updated; }); await audit(request, "FMEA_UPDATE", "FmeaAssessment", id, { version: nextVersion }); return envelope(assessment); });
  app.delete("/api/v1/fmea/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.delete"); const { id } = parse(idParam, request.params); await getFmea(id, organizationId); await prisma.fmeaAssessment.update({ where: { id }, data: { deletedAt: new Date(), status: "ARCHIVED" } }); await audit(request, "FMEA_DELETE", "FmeaAssessment", id); return envelope({ success: true }); });
  app.get("/api/v1/fmea/:id/history", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); const { id } = parse(idParam, request.params); await getFmea(id, organizationId); return envelope(await prisma.fmeaVersion.findMany({ where: { assessmentId: id }, orderBy: { version: "desc" } })); });
  app.post("/api/v1/fmea/:id/duplicate", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.create"); const { id } = parse(idParam, request.params); const current = await getFmea(id, organizationId); const code = `${current.code}-COPY-${Date.now().toString().slice(-6)}`; const copy = await prisma.fmeaAssessment.create({ data: { organizationId, projectId: current.projectId, activityId: current.activityId, title: `${current.title} (Copy)`, code, scope: current.scope, items: { create: current.items.map((source) => ({ rowNumber: source.rowNumber, processStep: source.processStep, failureMode: source.failureMode, effect: source.effect, cause: source.cause, preventiveControls: source.preventiveControls, detectionControls: source.detectionControls, severity: source.severity, occurrence: source.occurrence, detection: source.detection, rpn: source.rpn, riskLevel: source.riskLevel, recommendation: source.recommendation, residualSeverity: source.residualSeverity, residualOccurrence: source.residualOccurrence, residualDetection: source.residualDetection, residualRpn: source.residualRpn })) } } }); await audit(request, "FMEA_DUPLICATE", "FmeaAssessment", copy.id, { sourceId: id }); return reply.code(201).send(envelope(copy)); });
  app.post("/api/v1/fmea/:id/items", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.update"); const { id } = parse(idParam, request.params); const assessment = await prisma.fmeaAssessment.findFirst({ where: { id, organizationId, deletedAt: null }, include: { organization: true } }); if (!assessment) throw Object.assign(new Error("FMEA not found"), { statusCode: 404 }); const body = parse(fmeaItemBody, request.body); const rpn = calculateRpn(body.severity, body.occurrence, body.detection); const residualRpn = body.residualSeverity && body.residualOccurrence && body.residualDetection ? calculateRpn(body.residualSeverity, body.residualOccurrence, body.residualDetection) : null; const item = await prisma.fmeaItem.create({ data: { assessmentId: id, ...body, rpn, residualRpn, riskLevel: riskLevel(rpn, { medium: assessment.organization.riskMedium, high: assessment.organization.riskHigh, critical: assessment.organization.riskCritical }) } }); await audit(request, "FMEA_ITEM_CREATE", "FmeaItem", item.id); return reply.code(201).send(envelope(item)); });
  app.patch("/api/v1/fmea/:id/items/:itemId", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.update"); const params = parse(z.object({ id: z.string().uuid(), itemId: z.string().uuid() }), request.params); await getFmea(params.id, organizationId); const current = await prisma.fmeaItem.findFirst({ where: { id: params.itemId, assessmentId: params.id } }); if (!current) throw Object.assign(new Error("FMEA item not found"), { statusCode: 404 }); const body = parse(fmeaItemBody.partial(), request.body); const severity = body.severity ?? current.severity, occurrence = body.occurrence ?? current.occurrence, detection = body.detection ?? current.detection; const rpn = calculateRpn(severity, occurrence, detection); const residualSeverity = body.residualSeverity === undefined ? current.residualSeverity : body.residualSeverity; const residualOccurrence = body.residualOccurrence === undefined ? current.residualOccurrence : body.residualOccurrence; const residualDetection = body.residualDetection === undefined ? current.residualDetection : body.residualDetection; const residualRpn = residualSeverity && residualOccurrence && residualDetection ? calculateRpn(residualSeverity, residualOccurrence, residualDetection) : null; const org = await prisma.organization.findUniqueOrThrow({ where: { id: organizationId } }); return envelope(await prisma.fmeaItem.update({ where: { id: params.itemId }, data: { ...body, rpn, residualRpn, riskLevel: riskLevel(rpn, { medium: org.riskMedium, high: org.riskHigh, critical: org.riskCritical }) } })); });
  app.delete("/api/v1/fmea/:id/items/:itemId", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.update"); const params = parse(z.object({ id: z.string().uuid(), itemId: z.string().uuid() }), request.params); await getFmea(params.id, organizationId); const result = await prisma.fmeaItem.deleteMany({ where: { id: params.itemId, assessmentId: params.id } }); if (!result.count) throw Object.assign(new Error("FMEA item not found"), { statusCode: 404 }); return envelope({ success: true }); });

  app.get("/api/v1/rula", { preHandler: authenticate }, async (request) => envelope(await prisma.rulaAssessment.findMany({ where: { organizationId: requireOrg(request) }, include: { project: { select: { name: true, code: true } } }, orderBy: { updatedAt: "desc" } })));
  app.get("/api/v1/rula/:id", { preHandler: authenticate }, async (request) => envelope(await getRula(parse(idParam, request.params).id, requireOrg(request))));
  app.post("/api/v1/rula", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.create"); const body = parse(rulaBody, request.body); await ensureProject(body.projectId, organizationId); await ensureActivity(body.activityId, body.projectId, organizationId); const result = calculateRula(body.inputs as RulaInput); const assessment = await prisma.rulaAssessment.create({ data: { organizationId, ...body, inputs: json(body.inputs), score: result.score, actionLevel: result.actionLevel, explanation: result.explanation } }); await prisma.rulaVersion.create({ data: { assessmentId: assessment.id, version: 1, snapshot: json({ ...assessment, trace: result.trace }), createdBy: request.actor!.userId } }); await audit(request, "RULA_CREATE", "RulaAssessment", assessment.id); return reply.code(201).send(envelope({ ...assessment, trace: result.trace })); });
  app.patch("/api/v1/rula/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.update"); const { id } = parse(idParam, request.params); const current = await getRula(id, organizationId); const body = parse(rulaBody.partial(), request.body); const projectId = body.projectId ?? current.projectId; await ensureProject(projectId, organizationId); await ensureActivity(body.activityId === undefined ? current.activityId : body.activityId, projectId, organizationId); const inputs = (body.inputs ?? current.inputs) as unknown as RulaInput; const result = calculateRula(inputs); const nextVersion = current.version + 1; const nextSnapshot = { ...current, ...body, projectId, activityId: body.activityId === undefined ? current.activityId : body.activityId, inputs, score: result.score, actionLevel: result.actionLevel, explanation: result.explanation, version: nextVersion }; const assessment = await prisma.$transaction(async (tx) => { await tx.rulaVersion.upsert({ where: { assessmentId_version: { assessmentId: id, version: current.version } }, update: {}, create: { assessmentId: id, version: current.version, snapshot: json(current), createdBy: request.actor!.userId } }); const updated = await tx.rulaAssessment.update({ where: { id }, data: { ...body, ...(body.inputs ? { inputs: json(body.inputs) } : {}), score: result.score, actionLevel: result.actionLevel, explanation: result.explanation, version: nextVersion } }); await tx.rulaVersion.upsert({ where: { assessmentId_version: { assessmentId: id, version: nextVersion } }, update: {}, create: { assessmentId: id, version: nextVersion, snapshot: json(nextSnapshot), createdBy: request.actor!.userId } }); return updated; }); await audit(request, "RULA_UPDATE", "RulaAssessment", id, { version: assessment.version }); return envelope({ ...assessment, trace: result.trace }); });
  app.delete("/api/v1/rula/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.delete"); const { id } = parse(idParam, request.params); await getRula(id, organizationId); await prisma.rulaAssessment.update({ where: { id }, data: { status: "ARCHIVED" } }); await audit(request, "RULA_DELETE", "RulaAssessment", id); return envelope({ success: true }); });
  app.get("/api/v1/rula/:id/history", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); const { id } = parse(idParam, request.params); await getRula(id, organizationId); return envelope(await prisma.rulaVersion.findMany({ where: { assessmentId: id }, orderBy: { version: "desc" } })); });
  app.post("/api/v1/rula/:id/duplicate", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "assessments.create"); const { id } = parse(idParam, request.params); const current = await getRula(id, organizationId); const copy = await prisma.rulaAssessment.create({ data: { organizationId, projectId: current.projectId, activityId: current.activityId, title: `${current.title} (Copy)`, subjectCode: current.subjectCode, bodySide: current.bodySide, inputs: current.inputs as Prisma.InputJsonValue, score: current.score, actionLevel: current.actionLevel, explanation: current.explanation } }); await audit(request, "RULA_DUPLICATE", "RulaAssessment", copy.id, { sourceId: id }); return reply.code(201).send(envelope(copy)); });
}
