import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authenticate } from "../auth-guard.js";
import { audit, envelope, pageParams, parse, prisma, requireOrg, requirePermission } from "../core.js";

const nullableText = z.preprocess((value) => value === "" ? null : value, z.string().nullable().optional());
const nullableUuid = z.preprocess((value) => value === "" ? null : value, z.string().uuid().nullable().optional());
const projectBody = z.object({ name: z.string().trim().min(2), code: z.string().trim().min(2).max(40), description: nullableText, status: z.enum(["DRAFT", "ACTIVE", "ON_HOLD", "COMPLETED", "ARCHIVED"]).optional(), startDate: z.preprocess((value) => value === "" ? null : value, z.coerce.date().nullable().optional()), endDate: z.preprocess((value) => value === "" ? null : value, z.coerce.date().nullable().optional()) });
const processBody = z.object({ projectId: z.string().uuid(), name: z.string().trim().min(2), description: nullableText, parentId: nullableUuid });
const activityBody = z.object({ projectId: z.string().uuid(), processId: nullableUuid, title: z.string().trim().min(2), jobTitle: nullableText, location: nullableText, description: nullableText, hazards: nullableText });

async function ensureProject(projectId: string, organizationId: string) {
  const project = await prisma.project.findFirst({ where: { id: projectId, organizationId, deletedAt: null } });
  if (!project) throw Object.assign(new Error("Project not found"), { statusCode: 404, code: "NOT_FOUND" });
  return project;
}

async function ensureProcess(processId: string, organizationId: string, projectId: string, selfId?: string) {
  if (selfId && processId === selfId) throw Object.assign(new Error("A process cannot be its own parent"), { statusCode: 400, code: "INVALID_PARENT" });
  const process = await prisma.process.findFirst({ where: { id: processId, organizationId, projectId, deletedAt: null } });
  if (!process) throw Object.assign(new Error("The selected process does not belong to this project"), { statusCode: 400, code: "PROCESS_PROJECT_MISMATCH" });
  return process;
}

async function validateProcessHierarchy(processId: string, parentId: string | null | undefined, organizationId: string, projectId: string) {
  if (!parentId) return;
  await ensureProcess(parentId, organizationId, projectId, processId);
  let cursor: string | null = parentId;
  const visited = new Set<string>();
  while (cursor) {
    if (cursor === processId) throw Object.assign(new Error("Circular process hierarchy is not allowed"), { statusCode: 400, code: "PROCESS_CYCLE" });
    if (visited.has(cursor)) break;
    visited.add(cursor);
    const current: { parentId: string | null } | null = await prisma.process.findFirst({ where: { id: cursor, organizationId, projectId, deletedAt: null }, select: { parentId: true } });
    cursor = current?.parentId ?? null;
  }
}

export async function registerProjectRoutes(app: FastifyInstance) {
  app.get("/api/v1/projects", { preHandler: authenticate }, async (request) => {
    const organizationId = requireOrg(request); requirePermission(request, "projects.read"); const q = pageParams(request.query);
    const where = { organizationId, deletedAt: null, ...(q.search ? { OR: [{ name: { contains: q.search } }, { code: { contains: q.search } }] } : {}) };
    const [data, total] = await Promise.all([prisma.project.findMany({ where, skip: (q.page - 1) * q.limit, take: q.limit, orderBy: { updatedAt: "desc" } }), prisma.project.count({ where })]);
    return envelope(data, { ...q, total });
  });
  app.post("/api/v1/projects", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const body = parse(projectBody, request.body); const project = await prisma.project.create({ data: { organizationId, ...body } }); await audit(request, "PROJECT_CREATE", "Project", project.id); return reply.code(201).send(envelope(project)); });
  app.get("/api/v1/projects/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.read"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const project = await prisma.project.findFirst({ where: { id, organizationId, deletedAt: null }, include: { processes: { where: { deletedAt: null } }, activities: { where: { deletedAt: null } } } }); if (!project) throw Object.assign(new Error("Project not found"), { statusCode: 404, code: "NOT_FOUND" }); return envelope(project); });
  app.patch("/api/v1/projects/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); await ensureProject(id, organizationId); const body = parse(projectBody.partial(), request.body); const project = await prisma.project.update({ where: { id }, data: body }); await audit(request, "PROJECT_UPDATE", "Project", id, body); return envelope(project); });
  app.delete("/api/v1/projects/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); await ensureProject(id, organizationId); await prisma.project.update({ where: { id }, data: { deletedAt: new Date(), status: "ARCHIVED" } }); await audit(request, "PROJECT_DELETE", "Project", id); return envelope({ success: true }); });

  app.get("/api/v1/processes", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.read"); const q = parse(z.object({ projectId: z.string().uuid().optional() }), request.query); if (q.projectId) await ensureProject(q.projectId, organizationId); return envelope(await prisma.process.findMany({ where: { organizationId, deletedAt: null, ...(q.projectId ? { projectId: q.projectId } : {}) }, orderBy: { updatedAt: "desc" } })); });
  app.post("/api/v1/processes", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const body = parse(processBody, request.body); await ensureProject(body.projectId, organizationId); await validateProcessHierarchy("", body.parentId, organizationId, body.projectId); const process = await prisma.process.create({ data: { organizationId, ...body } }); await audit(request, "PROCESS_CREATE", "Process", process.id); return reply.code(201).send(envelope(process)); });
  app.patch("/api/v1/processes/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const existing = await prisma.process.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw Object.assign(new Error("Process not found"), { statusCode: 404, code: "NOT_FOUND" }); const body = parse(processBody.partial(), request.body); const projectId = body.projectId ?? existing.projectId; await ensureProject(projectId, organizationId); await validateProcessHierarchy(id, body.parentId === undefined ? existing.parentId : body.parentId, organizationId, projectId); if (body.projectId && body.projectId !== existing.projectId) { const children = await prisma.process.count({ where: { parentId: id, deletedAt: null } }); const activities = await prisma.activity.count({ where: { processId: id, deletedAt: null } }); if (children || activities) throw Object.assign(new Error("Move child processes and activities before changing the project"), { statusCode: 409, code: "PROCESS_HAS_DEPENDENCIES" }); } const updated = await prisma.process.update({ where: { id }, data: body }); await audit(request, "PROCESS_UPDATE", "Process", id, body); return envelope(updated); });
  app.delete("/api/v1/processes/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const existing = await prisma.process.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw Object.assign(new Error("Process not found"), { statusCode: 404, code: "NOT_FOUND" }); const children = await prisma.process.count({ where: { parentId: id, deletedAt: null } }); const activities = await prisma.activity.count({ where: { processId: id, deletedAt: null } }); if (children || activities) throw Object.assign(new Error("This process has child processes or activities"), { statusCode: 409, code: "PROCESS_HAS_DEPENDENCIES" }); await prisma.process.update({ where: { id }, data: { deletedAt: new Date() } }); await audit(request, "PROCESS_DELETE", "Process", id); return envelope({ success: true }); });

  app.get("/api/v1/activities", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.read"); const q = parse(z.object({ projectId: z.string().uuid().optional(), processId: z.string().uuid().optional() }), request.query); if (q.projectId) await ensureProject(q.projectId, organizationId); return envelope(await prisma.activity.findMany({ where: { organizationId, deletedAt: null, ...(q.projectId ? { projectId: q.projectId } : {}), ...(q.processId ? { processId: q.processId } : {}) }, orderBy: { updatedAt: "desc" } })); });
  app.post("/api/v1/activities", { preHandler: authenticate }, async (request, reply) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const body = parse(activityBody, request.body); await ensureProject(body.projectId, organizationId); if (body.processId) await ensureProcess(body.processId, organizationId, body.projectId); const activity = await prisma.activity.create({ data: { organizationId, ...body } }); await audit(request, "ACTIVITY_CREATE", "Activity", activity.id); return reply.code(201).send(envelope(activity)); });
  app.patch("/api/v1/activities/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const existing = await prisma.activity.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw Object.assign(new Error("Activity not found"), { statusCode: 404, code: "NOT_FOUND" }); const body = parse(activityBody.partial(), request.body); const projectId = body.projectId ?? existing.projectId; await ensureProject(projectId, organizationId); const processId = body.processId === undefined ? existing.processId : body.processId; if (processId) await ensureProcess(processId, organizationId, projectId); const updated = await prisma.activity.update({ where: { id }, data: body }); await audit(request, "ACTIVITY_UPDATE", "Activity", id, body); return envelope(updated); });
  app.delete("/api/v1/activities/:id", { preHandler: authenticate }, async (request) => { const organizationId = requireOrg(request); requirePermission(request, "projects.manage"); const { id } = parse(z.object({ id: z.string().uuid() }), request.params); const existing = await prisma.activity.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw Object.assign(new Error("Activity not found"), { statusCode: 404, code: "NOT_FOUND" }); const assessments = await prisma.fmeaAssessment.count({ where: { activityId: id, deletedAt: null } }) + await prisma.rulaAssessment.count({ where: { activityId: id, status: { not: "ARCHIVED" } } }); if (assessments) throw Object.assign(new Error("This activity is used by an assessment"), { statusCode: 409, code: "ACTIVITY_HAS_ASSESSMENTS" }); await prisma.activity.update({ where: { id }, data: { deletedAt: new Date() } }); await audit(request, "ACTIVITY_DELETE", "Activity", id); return envelope({ success: true }); });
}
